/**
 * A thousand ordinary sentences, two for every word in `common-words.js`.
 *
 * The reading deck has real nineteenth-century prose and the phrasebook has
 * the things you say in a shop. This is the middle: plain sentences of the
 * kind that make up most of a day, chosen so that the five hundred words
 * worth knowing each turn up twice, in two different shapes.
 *
 * Two sentences rather than one because a word met once is a word you have
 * seen, and a word met in two different sentences is a word you are starting
 * to own — *je pense à toi* and *qu'est-ce que tu en penses ?* are the same
 * verb doing different work.
 *
 * Written for this app. Short on purpose: a sentence you can hold in your
 * head is a sentence you can answer before the bus comes.
 *
 * Each row is one word and its two sentences, which is what keeps the
 * coverage honest — a word cannot quietly lose its examples.
 */

import { WORDS, BANDS } from './common-words.js';

const RAW = [
  ['être', 'Ce doit être une erreur.', 'That must be a mistake.', 'Nous sommes en retard.', 'We’re late.'],
  ['avoir', 'Vous avez raison.', 'You’re right.', 'Il faut avoir de la patience.', 'You have to have patience.'],
  ['faire', 'Qu’est-ce que tu fais ce soir ?', 'What are you doing this evening?', 'Je vais faire les courses.', 'I’m going to do the shopping.'],
  ['dire', 'Je ne sais pas quoi dire.', 'I don’t know what to say.', 'Elle m’a dit la vérité.', 'She told me the truth.'],
  ['aller', 'On y va tout de suite.', 'We’re going right now.', 'Nous allons à la mer en août.', 'We go to the seaside in August.'],
  ['voir', 'Je vais voir ce que je peux faire.', 'I’ll see what I can do.', 'Tu as vu mes clés ?', 'Have you seen my keys?'],
  ['savoir', 'Je n’en sais rien.', 'I have no idea.', 'Vous savez où il habite ?', 'Do you know where he lives?'],
  ['pouvoir', 'Vous pouvez entrer.', 'You can come in.', 'Je n’ai pas pu venir hier.', 'I couldn’t come yesterday.'],
  ['vouloir', 'Je voudrais un café.', 'I’d like a coffee.', 'Ils ne veulent pas attendre.', 'They don’t want to wait.'],
  ['venir', 'Tu viens avec nous ?', 'Are you coming with us?', 'Tu peux venir demain ?', 'Can you come tomorrow?'],
  ['devoir', 'Je dois partir tôt demain.', 'I have to leave early tomorrow.', 'Tu devrais lui parler.', 'You should talk to him.'],
  ['falloir', 'Il faut réserver à l’avance.', 'You have to book in advance.', 'Il fallait le dire plus tôt.', 'You should have said so sooner.'],
  ['croire', 'Je crois qu’il a raison.', 'I think he’s right.', 'On ne m’a pas cru.', 'They didn’t believe me.'],
  ['trouver', 'Je ne trouve pas mon billet.', 'I can’t find my ticket.', 'Comment tu trouves ce film ?', 'What do you think of this film?'],
  ['donner', 'Donne-moi cinq minutes.', 'Give me five minutes.', 'Elle m’a donné son numéro.', 'She gave me her number.'],
  ['prendre', 'Je prends le train de huit heures.', 'I’m taking the eight o’clock train.', 'Prenez votre temps.', 'Take your time.'],
  ['parler', 'On peut parler une minute ?', 'Can we talk for a minute?', 'Il parle trop vite.', 'He talks too fast.'],
  ['aimer', 'J’aime beaucoup ce quartier.', 'I really like this neighbourhood.', 'Elle n’aime pas le bruit.', 'She doesn’t like noise.'],
  ['passer', 'Je passe te prendre à midi.', 'I’ll come and get you at midday.', 'Le temps passe vite.', 'Time goes quickly.'],
  ['mettre', 'Mets ton manteau, il fait froid.', 'Put your coat on, it’s cold.', 'J’ai mis les clés sur la table.', 'I put the keys on the table.'],
  ['demander', 'Je vais lui demander.', 'I’ll ask him.', 'Elle m’a demandé de l’aide.', 'She asked me for help.'],
  ['tenir', 'Tiens-moi ça une seconde.', 'Hold this for me a second.', 'Tu peux tenir la porte ?', 'Can you hold the door?'],
  ['sembler', 'Ça me semble juste.', 'That seems right to me.', 'Elle semblait fatiguée.', 'She seemed tired.'],
  ['laisser', 'Laisse-moi t’expliquer.', 'Let me explain.', 'J’ai laissé mon sac au bureau.', 'I left my bag at the office.'],
  ['rester', 'Je reste encore deux jours.', 'I’m staying two more days.', 'Il ne reste plus de pain.', 'There’s no bread left.'],
  ['penser', 'Je pense à toi.', 'I’m thinking of you.', 'Qu’est-ce que tu en penses ?', 'What do you think of it?'],
  ['entendre', 'Je n’entends rien.', 'I can’t hear anything.', 'Tu as entendu ce bruit ?', 'Did you hear that noise?'],
  ['regarder', 'On regarde un film ce soir ?', 'Shall we watch a film tonight?', 'Il me regardait sans rien dire.', 'He was looking at me without saying anything.'],
  ['répondre', 'Personne n’a répondu.', 'Nobody answered.', 'Réponds-moi quand tu peux.', 'Get back to me when you can.'],
  ['connaître', 'Tu connais ce restaurant ?', 'Do you know this restaurant?', 'Je connais bien la ville.', 'I know the town well.'],
  ['arriver', 'J’arrive dans dix minutes.', 'I’ll be there in ten minutes.', 'Qu’est-ce qui est arrivé ?', 'What happened?'],
  ['attendre', 'Attends-moi devant la gare.', 'Wait for me in front of the station.', 'On attend depuis une heure.', 'We’ve been waiting an hour.'],
  ['vivre', 'Ils vivent à la campagne.', 'They live in the countryside.', 'C’est difficile à vivre.', 'It’s hard to live with.'],
  ['chercher', 'Je cherche la sortie.', 'I’m looking for the way out.', 'Va chercher ta sœur.', 'Go and fetch your sister.'],
  ['sortir', 'On sort ce soir ?', 'Shall we go out tonight?', 'Il est sorti sans rien dire.', 'He left without a word.'],
  ['comprendre', 'Je ne comprends pas la question.', 'I don’t understand the question.', 'Tu as compris ?', 'Did you get it?'],
  ['porter', 'Elle porte une robe bleue.', 'She’s wearing a blue dress.', 'Tu peux porter ce sac ?', 'Can you carry this bag?'],
  ['devenir', 'C’est devenu impossible.', 'It has become impossible.', 'Qu’est-ce qu’il devient ?', 'What’s he up to these days?'],
  ['entrer', 'Entrez, c’est ouvert.', 'Come in, it’s open.', 'Il est entré sans frapper.', 'He came in without knocking.'],
  ['écrire', 'Je vais lui écrire ce soir.', 'I’ll write to him tonight.', 'Ça s’écrit comment ?', 'How do you spell it?'],
  ['appeler', 'Appelle-moi ce soir.', 'Call me tonight.', 'Comment ça s’appelle ?', 'What’s it called?'],
  ['tomber', 'Attention, tu vas tomber.', 'Careful, you’re going to fall.', 'La nuit tombe tôt en hiver.', 'It gets dark early in winter.'],
  ['suivre', 'Suivez-moi, s’il vous plaît.', 'Follow me, please.', 'Je n’ai pas suivi la fin.', 'I didn’t follow the end of it.'],
  ['commencer', 'Le film commence à vingt heures.', 'The film starts at eight.', 'On commence par quoi ?', 'What shall we start with?'],
  ['jouer', 'Les enfants jouent dehors.', 'The children are playing outside.', 'Tu joues d’un instrument ?', 'Do you play an instrument?'],
  ['perdre', 'J’ai perdu mon parapluie.', 'I’ve lost my umbrella.', 'On perd du temps.', 'We’re wasting time.'],
  ['apprendre', 'J’apprends le français depuis deux ans.', 'I’ve been learning French for two years.', 'Elle apprend vite.', 'She learns quickly.'],
  ['oublier', 'N’oublie pas ton passeport.', 'Don’t forget your passport.', 'J’ai oublié son nom.', 'I’ve forgotten his name.'],
  ['travailler', 'Elle travaille dans un hôpital.', 'She works in a hospital.', 'Je travaille de chez moi.', 'I work from home.'],
  ['manger', 'On mange à quelle heure ?', 'What time are we eating?', 'Je n’ai rien mangé depuis ce matin.', 'I haven’t eaten since this morning.'],
  ['temps', 'Je n’ai pas le temps.', 'I don’t have time.', 'Quel temps fait-il ?', 'What’s the weather like?'],
  ['jour', 'À un de ces jours !', 'See you one of these days!', 'Il travaille tous les jours.', 'He works every day.'],
  ['homme', 'Un homme vous attend en bas.', 'A man is waiting for you downstairs.', 'C’est un homme très gentil.', 'He’s a very kind man.'],
  ['femme', 'Sa femme est médecin.', 'His wife is a doctor.', 'Une femme m’a aidé.', 'A woman helped me.'],
  ['enfant', 'Ils ont trois enfants.', 'They have three children.', 'Quand j’étais enfant, j’habitais ici.', 'When I was a child I lived here.'],
  ['chose', 'J’ai une chose à te dire.', 'I have something to tell you.', 'C’est la même chose.', 'It’s the same thing.'],
  ['vie', 'C’est la vie.', 'That’s life.', 'Il a passé sa vie ici.', 'He spent his life here.'],
  ['monde', 'Il y a trop de monde.', 'There are too many people.', 'Tout le monde le sait.', 'Everybody knows.'],
  ['pays', 'C’est un beau pays.', 'It’s a beautiful country.', 'Dans quel pays êtes-vous né ?', 'What country were you born in?'],
  ['ville', 'La ville est calme le dimanche.', 'The town is quiet on Sundays.', 'Je vais en ville ce matin.', 'I’m going into town this morning.'],
  ['maison', 'Je rentre à la maison.', 'I’m going home.', 'Leur maison est près du parc.', 'Their house is near the park.'],
  ['eau', 'Une carafe d’eau, s’il vous plaît.', 'A jug of tap water, please.', 'L’eau est froide.', 'The water is cold.'],
  ['main', 'Donne-moi la main.', 'Give me your hand.', 'Il avait un livre à la main.', 'He had a book in his hand.'],
  ['nuit', 'Bonne nuit.', 'Good night.', 'J’ai mal dormi cette nuit.', 'I slept badly last night.'],
  ['matin', 'Je pars demain matin.', 'I’m leaving tomorrow morning.', 'Le matin, je bois un café.', 'In the morning I have a coffee.'],
  ['soir', 'On se voit ce soir.', 'See you this evening.', 'Le soir, il fait plus frais.', 'It’s cooler in the evening.'],
  ['année', 'Bonne année !', 'Happy New Year!', 'L’année dernière, il neigeait.', 'Last year it was snowing.'],
  ['mois', 'Je pars le mois prochain.', 'I’m leaving next month.', 'Ça fait deux mois qu’il est parti.', 'He left two months ago.'],
  ['semaine', 'À la semaine prochaine.', 'See you next week.', 'Je travaille cinq jours par semaine.', 'I work five days a week.'],
  ['heure', 'Quelle heure est-il ?', 'What time is it?', 'Il est arrivé à l’heure.', 'He arrived on time.'],
  ['moment', 'Un moment, s’il vous plaît.', 'One moment, please.', 'Ce n’est pas le bon moment.', 'It’s not the right moment.'],
  ['fois', 'C’est la première fois.', 'It’s the first time.', 'Je l’ai vu deux fois.', 'I’ve seen it twice.'],
  ['ami', 'C’est un ami de la famille.', 'He’s a family friend.', 'Je pars avec des amis.', 'I’m going away with friends.'],
  ['gens', 'Les gens sont pressés ici.', 'People are in a hurry here.', 'Il y avait beaucoup de gens.', 'There were a lot of people.'],
  ['personne', 'Il n’y a personne.', 'There’s nobody here.', 'Une personne sur deux le fait.', 'One person in two does it.'],
  ['nom', 'Quel est votre nom ?', 'What is your name?', 'Je ne retiens jamais les noms.', 'I never remember names.'],
  ['mot', 'Je n’ai pas compris ce mot.', 'I didn’t understand that word.', 'Il est parti sans un mot.', 'He left without a word.'],
  ['question', 'Bonne question.', 'Good question.', 'Ce n’est pas la question.', 'That’s not the point.'],
  ['raison', 'Tu as raison.', 'You’re right.', 'Pour une raison ou pour une autre, il a refusé.', 'For one reason or another, he refused.'],
  ['histoire', 'Raconte-moi l’histoire.', 'Tell me the story.', 'C’est une longue histoire.', 'It’s a long story.'],
  ['grand', 'C’est une grande maison.', 'It’s a big house.', 'Il est plus grand que moi.', 'He’s taller than me.'],
  ['petit', 'On prend un petit café ?', 'Shall we have a quick coffee?', 'C’est un petit village.', 'It’s a small village.'],
  ['bon', 'C’est très bon.', 'It’s very good.', 'Bonne journée !', 'Have a good day!'],
  ['mauvais', 'Il fait mauvais aujourd’hui.', 'The weather is bad today.', 'C’était une mauvaise idée.', 'It was a bad idea.'],
  ['nouveau', 'Il y a un nouveau restaurant.', 'There’s a new restaurant.', 'À nouveau, merci.', 'Thank you again.'],
  ['vieux', 'C’est un vieux film.', 'It’s an old film.', 'Mon vieux vélo marche encore.', 'My old bike still works.'],
  ['jeune', 'Elle est plus jeune que lui.', 'She’s younger than him.', 'Beaucoup de jeunes habitent ici.', 'A lot of young people live here.'],
  ['beau', 'Il fait beau aujourd’hui.', 'The weather is nice today.', 'C’est un très beau jardin.', 'It’s a very beautiful garden.'],
  ['même', 'Il porte le même manteau que moi.', 'He’s wearing the same coat as me.', 'Il est venu quand même.', 'He came anyway.'],
  ['autre', 'Vous avez une autre taille ?', 'Do you have another size?', 'Les autres arrivent bientôt.', 'The others are arriving soon.'],
  ['bien', 'Ça va bien, merci.', 'I’m well, thank you.', 'Il travaille bien.', 'He works well.'],
  ['très', 'C’est très gentil.', 'That’s very kind.', 'Je suis très fatigué.', 'I’m very tired.'],
  ['trop', 'C’est trop cher.', 'It’s too expensive.', 'Il y a trop de bruit.', 'There’s too much noise.'],
  ['toujours', 'Il est toujours en retard.', 'He’s always late.', 'Tu habites toujours à Lyon ?', 'Do you still live in Lyon?'],
  ['jamais', 'Je n’y suis jamais allé.', 'I’ve never been there.', 'On ne sait jamais.', 'You never know.'],
  ['encore', 'Encore un café, s’il vous plaît.', 'Another coffee, please.', 'Il dort encore.', 'He’s still asleep.'],
  ['déjà', 'Tu as déjà fini ?', 'Have you finished already?', 'J’ai déjà vu ce film.', 'I’ve already seen this film.'],
  ['souvent', 'Je viens souvent ici.', 'I come here often.', 'Il pleut souvent en novembre.', 'It often rains in November.'],
  ['maintenant', 'On y va maintenant ?', 'Shall we go now?', 'Maintenant je comprends.', 'Now I understand.'],
  ['peut-être', 'Il viendra peut-être demain.', 'He may come tomorrow.', 'Peut-être que tu as raison.', 'Maybe you’re right.'],
  ['rendre', 'Je dois rendre ce livre.', 'I have to give this book back.', 'Ça me rend triste.', 'It makes me sad.'],
  ['paraître', 'Il paraît qu’il va pleuvoir.', 'Apparently it’s going to rain.', 'Elle paraît plus jeune.', 'She looks younger.'],
  ['sentir', 'Ça sent bon dans la cuisine.', 'It smells good in the kitchen.', 'Je ne me sens pas bien.', 'I don’t feel well.'],
  ['revenir', 'Je reviens dans cinq minutes.', 'I’ll be back in five minutes.', 'Il est revenu très tard.', 'He came back very late.'],
  ['monter', 'On monte par l’escalier.', 'We’ll go up by the stairs.', 'Les prix ont monté.', 'Prices have gone up.'],
  ['descendre', 'Je descends à la prochaine.', 'I’m getting off at the next stop.', 'Descends, on t’attend !', 'Come down, we’re waiting for you!'],
  ['ouvrir', 'Tu peux ouvrir la fenêtre ?', 'Can you open the window?', 'Le musée ouvre à dix heures.', 'The museum opens at ten.'],
  ['fermer', 'N’oublie pas de fermer à clé.', 'Don’t forget to lock up.', 'La boulangerie est fermée le lundi.', 'The bakery is closed on Mondays.'],
  ['lire', 'Je lis avant de dormir.', 'I read before going to sleep.', 'Qu’est-ce que tu aimes lire ?', 'What do you like reading?'],
  ['boire', 'Qu’est-ce que tu bois ?', 'What are you drinking?', 'Il ne boit pas d’alcool.', 'He doesn’t drink alcohol.'],
  ['dormir', 'J’ai bien dormi.', 'I slept well.', 'Les enfants dorment déjà.', 'The children are already asleep.'],
  ['courir', 'Je cours tous les matins.', 'I run every morning.', 'Ne cours pas dans le couloir.', 'Don’t run in the corridor.'],
  ['partir', 'Le train part dans dix minutes.', 'The train leaves in ten minutes.', 'Elle est partie sans moi.', 'She left without me.'],
  ['marcher', 'On peut y aller à pied.', 'We can walk there.', 'Ça ne marche pas.', 'It doesn’t work.'],
  ['arrêter', 'Arrête, ce n’est pas drôle.', 'Stop it, it’s not funny.', 'Le bus s’arrête devant l’école.', 'The bus stops in front of the school.'],
  ['choisir', 'C’est à toi de choisir.', 'It’s your choice.', 'J’ai choisi le poisson.', 'I chose the fish.'],
  ['finir', 'J’ai fini mon travail.', 'I’ve finished my work.', 'Le film finit tard.', 'The film ends late.'],
  ['réussir', 'Elle a réussi son examen.', 'She passed her exam.', 'Je n’ai pas réussi à le joindre.', 'I couldn’t get hold of him.'],
  ['essayer', 'Essaie encore une fois.', 'Try once more.', 'Je peux l’essayer ?', 'Can I try it on?'],
  ['expliquer', 'Tu peux m’expliquer la règle ?', 'Can you explain the rule to me?', 'Il m’a expliqué le chemin.', 'He explained the way to me.'],
  ['décider', 'On a décidé de rester.', 'We decided to stay.', 'C’est à vous de décider.', 'It’s up to you to decide.'],
  ['préférer', 'Je préfère le thé.', 'I prefer tea.', 'Tu préfères quel jour ?', 'Which day do you prefer?'],
  ['acheter', 'J’ai acheté du pain.', 'I bought some bread.', 'Où est-ce qu’on achète les billets ?', 'Where do you buy the tickets?'],
  ['payer', 'Je peux payer par carte ?', 'Can I pay by card?', 'C’est moi qui paie.', 'It’s on me.'],
  ['coûter', 'Combien ça coûte ?', 'How much does it cost?', 'Ça coûte moins cher en ligne.', 'It costs less online.'],
  ['changer', 'Rien n’a changé ici.', 'Nothing has changed here.', 'Je dois changer de train à Lyon.', 'I have to change trains at Lyon.'],
  ['garder', 'Garde la monnaie.', 'Keep the change.', 'Elle garde les enfants ce soir.', 'She’s looking after the children tonight.'],
  ['montrer', 'Montre-moi la photo.', 'Show me the photo.', 'Il m’a montré sa ville.', 'He showed me around his town.'],
  ['continuer', 'Continuez tout droit.', 'Carry straight on.', 'On continue demain.', 'We’ll carry on tomorrow.'],
  ['oser', 'Je n’ose pas lui dire.', 'I daren’t tell him.', 'Elle a osé demander.', 'She dared to ask.'],
  ['aider', 'Tu peux m’aider ?', 'Can you help me?', 'Il aide son voisin le samedi.', 'He helps his neighbour on Saturdays.'],
  ['habiter', 'J’habite près d’ici.', 'I live near here.', 'Ils habitent au troisième étage.', 'They live on the third floor.'],
  ['rencontrer', 'On s’est rencontrés à Paris.', 'We met in Paris.', 'J’ai rencontré ton frère hier.', 'I ran into your brother yesterday.'],
  ['inviter', 'Je t’invite.', 'It’s my treat.', 'Ils nous ont invités à dîner.', 'They invited us to dinner.'],
  ['envoyer', 'Je t’envoie l’adresse.', 'I’ll send you the address.', 'Elle a envoyé une carte.', 'She sent a card.'],
  ['recevoir', 'J’ai reçu ta lettre.', 'I got your letter.', 'On reçoit des amis ce soir.', 'We have friends coming round tonight.'],
  ['offrir', 'Je t’offre un café.', 'Let me buy you a coffee.', 'Qu’est-ce qu’on lui offre ?', 'What shall we get her?'],
  ['servir', 'Ça ne sert à rien.', 'It’s no use.', 'On sert le petit-déjeuner à sept heures.', 'Breakfast is served at seven.'],
  ['plaire', 'Ce film m’a beaucoup plu.', 'I liked that film a lot.', 'S’il vous plaît, une minute.', 'Excuse me, just a minute.'],
  ['manquer', 'Tu me manques.', 'I miss you.', 'Il manque une chaise.', 'There’s a chair missing.'],
  ['famille', 'Toute la famille est venue.', 'The whole family came.', 'J’ai de la famille dans le sud.', 'I have family in the south.'],
  ['père', 'Mon père est à la retraite.', 'My father is retired.', 'Il ressemble à son père.', 'He looks like his father.'],
  ['mère', 'Sa mère habite au Canada.', 'His mother lives in Canada.', 'J’appelle ma mère le dimanche.', 'I phone my mother on Sundays.'],
  ['frère', 'J’ai deux frères.', 'I have two brothers.', 'Mon frère travaille à Lille.', 'My brother works in Lille.'],
  ['sœur', 'Ma sœur est plus jeune.', 'My sister is younger.', 'Sa sœur vient de se marier.', 'His sister has just got married.'],
  ['fils', 'Leur fils a douze ans.', 'Their son is twelve.', 'C’est le fils du voisin.', 'He’s the neighbour’s son.'],
  ['fille', 'Sa fille étudie la médecine.', 'His daughter is studying medicine.', 'Une petite fille m’a montré le chemin.', 'A little girl showed me the way.'],
  ['voisin', 'Le voisin fait trop de bruit.', 'The neighbour makes too much noise.', 'Nos voisins sont très gentils.', 'Our neighbours are very kind.'],
  ['monsieur', 'Bonjour, monsieur.', 'Good morning, sir.', 'Un monsieur vous attend.', 'A gentleman is waiting for you.'],
  ['madame', 'Bonsoir, madame.', 'Good evening, madam.', 'Madame Leroy est absente aujourd’hui.', 'Mrs Leroy is away today.'],
  ['travail', 'J’ai beaucoup de travail.', 'I have a lot of work.', 'Il cherche du travail.', 'He’s looking for work.'],
  ['école', 'Les enfants sont à l’école.', 'The children are at school.', 'L’école est à côté de l’église.', 'The school is next to the church.'],
  ['livre', 'C’est un livre passionnant.', 'It’s a gripping book.', 'J’ai emprunté deux livres.', 'I borrowed two books.'],
  ['lettre', 'J’ai reçu une lettre ce matin.', 'I got a letter this morning.', 'Il écrit encore des lettres.', 'He still writes letters.'],
  ['réponse', 'Je n’ai pas eu de réponse.', 'I didn’t get an answer.', 'Sa réponse m’a surpris.', 'His answer surprised me.'],
  ['problème', 'Il y a un problème avec la clé.', 'There’s a problem with the key.', 'Pas de problème.', 'No problem.'],
  ['idée', 'Bonne idée !', 'Good idea!', 'Je n’en ai aucune idée.', 'I have no idea.'],
  ['exemple', 'Par exemple, le lundi.', 'On Mondays, for example.', 'Donne-moi un exemple.', 'Give me an example.'],
  ['place', 'Cette place est prise ?', 'Is this seat taken?', 'On se retrouve sur la place.', 'Let’s meet in the square.'],
  ['rue', 'J’habite dans cette rue.', 'I live on this street.', 'La rue est fermée aux voitures.', 'The street is closed to cars.'],
  ['route', 'La route est longue.', 'It’s a long drive.', 'Bonne route !', 'Have a safe trip!'],
  ['chemin', 'On a pris le mauvais chemin.', 'We took the wrong path.', 'Il m’a montré le chemin.', 'He showed me the way.'],
  ['voiture', 'Je viens en voiture.', 'I’m coming by car.', 'Leur voiture est en panne.', 'Their car has broken down.'],
  ['train', 'Le train a du retard.', 'The train is delayed.', 'Je prends le train de nuit.', 'I’m taking the night train.'],
  ['gare', 'On se retrouve à la gare.', 'Let’s meet at the station.', 'La gare est loin d’ici ?', 'Is the station far from here?'],
  ['billet', 'J’ai perdu mon billet.', 'I’ve lost my ticket.', 'Deux billets pour Nice, s’il vous plaît.', 'Two tickets to Nice, please.'],
  ['argent', 'Je n’ai pas d’argent sur moi.', 'I don’t have any money on me.', 'Il gagne bien sa vie.', 'He makes a good living.'],
  ['prix', 'Le prix est affiché.', 'The price is on display.', 'À ce prix-là, c’est une affaire.', 'At that price it’s a bargain.'],
  ['magasin', 'Le magasin ferme à sept heures.', 'The shop closes at seven.', 'Il y a un magasin au coin.', 'There’s a shop on the corner.'],
  ['marché', 'Le marché a lieu le mercredi.', 'The market is on Wednesdays.', 'J’achète mes légumes au marché.', 'I buy my vegetables at the market.'],
  ['porte', 'Ferme la porte, s’il te plaît.', 'Close the door, please.', 'Quelqu’un frappe à la porte.', 'Somebody’s knocking at the door.'],
  ['fenêtre', 'Ouvre la fenêtre, il fait chaud.', 'Open the window, it’s hot.', 'La fenêtre donne sur la cour.', 'The window looks onto the courtyard.'],
  ['table', 'La table est réservée.', 'The table is reserved.', 'Mets les verres sur la table.', 'Put the glasses on the table.'],
  ['chaise', 'Prends une chaise.', 'Pull up a chair.', 'Il manque deux chaises.', 'Two chairs are missing.'],
  ['lit', 'Le lit est trop mou.', 'The bed is too soft.', 'Il est encore au lit.', 'He’s still in bed.'],
  ['chambre', 'La chambre donne sur le jardin.', 'The room looks onto the garden.', 'J’ai réservé une chambre pour deux nuits.', 'I’ve booked a room for two nights.'],
  ['cuisine', 'On mange dans la cuisine.', 'We eat in the kitchen.', 'Il fait très bien la cuisine.', 'He’s a very good cook.'],
  ['jardin', 'Les enfants sont dans le jardin.', 'The children are in the garden.', 'Leur jardin est plein de fleurs.', 'Their garden is full of flowers.'],
  ['pain', 'Je vais chercher du pain.', 'I’m going to get some bread.', 'Il n’y a plus de pain.', 'There’s no bread left.'],
  ['café', 'On prend un café ?', 'Shall we have a coffee?', 'Le café du coin ouvre tôt.', 'The café on the corner opens early.'],
  ['repas', 'Le repas était excellent.', 'The meal was excellent.', 'On prend trois repas par jour.', 'We eat three meals a day.'],
  ['midi', 'On se voit à midi.', 'See you at midday.', 'Le magasin ferme entre midi et deux.', 'The shop closes between twelve and two.'],
  ['hier', 'Je l’ai vu hier soir.', 'I saw him last night.', 'Hier, il a plu toute la journée.', 'Yesterday it rained all day.'],
  ['demain', 'À demain !', 'See you tomorrow!', 'Demain, je commence tôt.', 'Tomorrow I start early.'],
  ['aujourd’hui', 'Aujourd’hui, je reste à la maison.', 'Today I’m staying at home.', 'Quel jour sommes-nous aujourd’hui ?', 'What day is it today?'],
  ['tard', 'Il est rentré très tard.', 'He got home very late.', 'Il n’est jamais trop tard.', 'It’s never too late.'],
  ['tôt', 'Je me lève tôt.', 'I get up early.', 'C’est encore tôt pour le dire.', 'It’s still early to say.'],
  ['vite', 'Ne parle pas si vite.', 'Don’t talk so fast.', 'Ça ira plus vite en métro.', 'It’ll be quicker by metro.'],
  ['ici', 'Signez ici, s’il vous plaît.', 'Sign here, please.', 'Il fait chaud ici.', 'It’s hot in here.'],
  ['là-bas', 'La sortie est là-bas.', 'The exit is over there.', 'On se retrouve là-bas.', 'We’ll meet over there.'],
  ['long', 'C’est un long week-end.', 'It’s a long weekend.', 'Le trajet est long.', 'It’s a long journey.'],
  ['court', 'Le film est court.', 'The film is short.', 'Elle a les cheveux courts.', 'She has short hair.'],
  ['gros', 'Il y a un gros problème.', 'There’s a big problem.', 'C’est un gros mot.', 'That’s a swear word.'],
  ['vrai', 'C’est vrai ?', 'Is that true?', 'Ce n’est pas son vrai nom.', 'That’s not his real name.'],
  ['faux', 'C’est un faux numéro.', 'It’s a wrong number.', 'Sa réponse est fausse.', 'Her answer is wrong.'],
  ['premier', 'C’est mon premier jour ici.', 'It’s my first day here.', 'J’habite au premier étage.', 'I live on the first floor.'],
  ['dernier', 'C’est le dernier train.', 'It’s the last train.', 'La semaine dernière, il faisait beau.', 'Last week the weather was nice.'],
  ['seul', 'Je préfère travailler seul.', 'I prefer working on my own.', 'C’est le seul qui reste.', 'It’s the only one left.'],
  ['cher', 'C’est trop cher pour moi.', 'It’s too expensive for me.', 'Les billets sont moins chers en semaine.', 'Tickets are cheaper on weekdays.'],
  ['facile', 'Ce n’est pas facile.', 'It isn’t easy.', 'L’exercice était facile.', 'The exercise was easy.'],
  ['difficile', 'C’est difficile à expliquer.', 'It’s hard to explain.', 'Il traverse une période difficile.', 'He’s going through a difficult patch.'],
  ['important', 'C’est important pour moi.', 'It’s important to me.', 'J’ai une réunion importante.', 'I have an important meeting.'],
  ['possible', 'Ce n’est pas possible.', 'That’s not possible.', 'Venez dès que possible.', 'Come as soon as possible.'],
  ['sûr', 'Tu es sûr ?', 'Are you sure?', 'Bien sûr !', 'Of course!'],
  ['prêt', 'Je suis prêt.', 'I’m ready.', 'Le repas est prêt.', 'The meal is ready.'],
  ['plein', 'Le train est plein.', 'The train is full.', 'Il y a plein de monde dehors.', 'There are loads of people outside.'],
  ['chaud', 'Il fait très chaud aujourd’hui.', 'It’s very hot today.', 'Attention, le plat est chaud.', 'Careful, the dish is hot.'],
  ['froid', 'J’ai froid.', 'I’m cold.', 'Le café est froid.', 'The coffee is cold.'],
  ['fort', 'Ne parle pas si fort.', 'Don’t talk so loudly.', 'Le vent est fort ce matin.', 'The wind is strong this morning.'],
  ['fatigué', 'Je suis fatigué.', 'I’m tired.', 'Elle avait l’air fatiguée.', 'She looked tired.'],
  ['heureux', 'Je suis heureux de te voir.', 'I’m happy to see you.', 'Ils ont l’air heureux.', 'They look happy.'],
  ['content', 'Je suis content du résultat.', 'I’m pleased with the result.', 'Elle n’est pas contente.', 'She isn’t happy about it.'],
  ['triste', 'C’est une histoire triste.', 'It’s a sad story.', 'Il avait l’air triste.', 'He looked sad.'],
  ['malade', 'Il est malade depuis lundi.', 'He’s been ill since Monday.', 'Je me sens un peu malade.', 'I feel a bit unwell.'],
  ['libre', 'Vous êtes libre ce soir ?', 'Are you free this evening?', 'Il n’y a plus de table libre.', 'There isn’t a free table left.'],
  ['occupé', 'Je suis très occupé cette semaine.', 'I’m very busy this week.', 'La ligne est occupée.', 'The line is engaged.'],
  ['gentil', 'C’est gentil, merci.', 'That’s kind, thank you.', 'Elle est très gentille avec moi.', 'She’s very kind to me.'],
  ['drôle', 'Ce n’est pas drôle.', 'It’s not funny.', 'Il m’est arrivé une drôle d’histoire.', 'A funny thing happened to me.'],
  ['prochain', 'À la prochaine fois.', 'Until next time.', 'Je descends au prochain arrêt.', 'I’m getting off at the next stop.'],
  ['différent', 'C’est très différent ici.', 'It’s very different here.', 'Ils ont des avis différents.', 'They have different opinions.'],
  ['assez', 'J’en ai assez.', 'I’ve had enough.', 'Il fait assez froid ce matin.', 'It’s quite cold this morning.'],
  ['mal', 'J’ai mal à la tête.', 'I have a headache.', 'Il a mal dormi.', 'He slept badly.'],
  ['mieux', 'Ça va mieux aujourd’hui.', 'I feel better today.', 'Il vaut mieux attendre.', 'It’s better to wait.'],
  ['parfois', 'Parfois je prends le bus.', 'Sometimes I take the bus.', 'Il est parfois difficile à comprendre.', 'He’s sometimes hard to understand.'],
  ['bientôt', 'À bientôt !', 'See you soon!', 'Elle arrive bientôt.', 'She’s arriving soon.'],
  ['ensemble', 'On y va ensemble ?', 'Shall we go together?', 'Ils travaillent ensemble depuis dix ans.', 'They’ve worked together for ten years.'],
  ['surtout', 'Surtout, ne dis rien.', 'Whatever you do, don’t say anything.', 'J’aime surtout le printemps.', 'I like spring best of all.'],
  ['vraiment', 'C’était vraiment bien.', 'It was really good.', 'Tu crois vraiment ?', 'Do you really think so?'],
  ['presque', 'C’est presque fini.', 'It’s almost finished.', 'Il est presque midi.', 'It’s nearly midday.'],
  ['enfin', 'Enfin, on arrive !', 'At last, we’re here!', 'Il a enfin répondu.', 'He finally answered.'],
  ['alors', 'Alors, on y va ?', 'So, shall we go?', 'Il pleuvait, alors on est restés.', 'It was raining, so we stayed in.'],
  ['donc', 'C’est donc toi qui as appelé.', 'So it was you who called.', 'Il était tard, donc je suis rentré.', 'It was late, so I went home.'],
  ['puis', 'On mange, puis on sort.', 'We’ll eat, then go out.', 'Et puis, il est parti.', 'And then he left.'],
  ['ensuite', 'Ensuite, tournez à gauche.', 'Then turn left.', 'On verra ensuite.', 'We’ll see after that.'],
  ['avant', 'Appelle-moi avant midi.', 'Call me before midday.', 'C’était mieux avant.', 'It was better before.'],
  ['après', 'On en parle après.', 'We’ll talk about it afterwards.', 'Après le film, on a marché un peu.', 'After the film we walked a little.'],
  ['pendant', 'Il a dormi pendant tout le trajet.', 'He slept the whole journey.', 'Pendant ce temps, je préparais le repas.', 'Meanwhile I was making the meal.'],
  ['depuis', 'J’attends depuis une heure.', 'I’ve been waiting for an hour.', 'Depuis quand tu le sais ?', 'How long have you known?'],
  ['quand', 'Quand est-ce que tu arrives ?', 'When are you arriving?', 'Préviens-moi quand tu seras prêt.', 'Let me know when you’re ready.'],
  ['comme', 'Fais comme tu veux.', 'Do as you like.', 'Il est comme son père.', 'He’s like his father.'],
  ['parce que', 'Je reste parce qu’il pleut.', 'I’m staying because it’s raining.', 'Parce que c’est comme ça.', 'Because that’s how it is.'],
  ['pourtant', 'Il fait froid, et pourtant c’est l’été.', 'It’s cold, and yet it’s summer.', 'Pourtant, je te l’avais dit.', 'And yet I did tell you.'],
  ['malgré', 'On est sortis malgré la pluie.', 'We went out despite the rain.', 'Malgré tout, il a réussi.', 'In spite of everything, he managed it.'],
  ['grâce à', 'J’ai trouvé grâce à toi.', 'I found it thanks to you.', 'Grâce à lui, tout est réglé.', 'Thanks to him it’s all sorted.'],
  ['à cause de', 'On est en retard à cause du train.', 'We’re late because of the train.', 'À cause de la pluie, le match est annulé.', 'The match is off because of the rain.'],
  ['combien', 'Ça fait combien ?', 'How much is that?', 'Combien de temps ça prend ?', 'How long does it take?'],
  ['pourquoi', 'Pourquoi tu ris ?', 'Why are you laughing?', 'Voilà pourquoi je suis venu.', 'That’s why I came.'],
  ['comment', 'Comment ça va ?', 'How are you?', 'Comment on fait ?', 'How do we do it?'],
  ['beaucoup', 'Merci beaucoup.', 'Thank you very much.', 'Il y a beaucoup de monde.', 'There are a lot of people.'],
  ['peu', 'Un peu de patience.', 'A bit of patience.', 'Il reste peu de temps.', 'There’s little time left.'],
  ['rappeler', 'Rappelle-moi demain.', 'Call me back tomorrow.', 'Ça me rappelle quelque chose.', 'That rings a bell.'],
  ['permettre', 'Vous permettez ?', 'May I?', 'Le beau temps nous a permis de sortir.', 'The fine weather let us go out.'],
  ['occuper', 'Je m’occupe du dîner.', 'I’ll see to dinner.', 'Cette place est occupée.', 'This seat is taken.'],
  ['compter', 'Compte jusqu’à dix.', 'Count to ten.', 'Je compte sur toi.', 'I’m counting on you.'],
  ['gagner', 'Notre équipe a gagné.', 'Our team won.', 'On gagne du temps comme ça.', 'We save time that way.'],
  ['utiliser', 'Je peux utiliser votre stylo ?', 'Can I use your pen?', 'Cette salle n’est plus utilisée.', 'This room isn’t used any more.'],
  ['ajouter', 'Ajoute un peu de sel.', 'Add a bit of salt.', 'Je n’ai rien à ajouter.', 'I have nothing to add.'],
  ['apporter', 'J’apporte le dessert.', 'I’ll bring dessert.', 'Apportez-moi l’addition, s’il vous plaît.', 'Bring me the bill, please.'],
  ['conduire', 'Elle conduit depuis vingt ans.', 'She’s been driving for twenty years.', 'Je ne sais pas conduire.', 'I can’t drive.'],
  ['construire', 'On construit un immeuble en face.', 'They’re putting up a block of flats opposite.', 'La maison a été construite en 1920.', 'The house was built in 1920.'],
  ['réfléchir', 'Laisse-moi réfléchir.', 'Let me think about it.', 'Réfléchis avant de répondre.', 'Think before you answer.'],
  ['remercier', 'Je vous remercie.', 'Thank you.', 'Il m’a remercié deux fois.', 'He thanked me twice.'],
  ['remarquer', 'Je n’avais rien remarqué.', 'I hadn’t noticed anything.', 'Tu as remarqué son accent ?', 'Did you notice his accent?'],
  ['rêver', 'J’ai rêvé de toi.', 'I dreamt about you.', 'Elle rêve de partir en Italie.', 'She dreams of going to Italy.'],
  ['chanter', 'Il chante sous la douche.', 'He sings in the shower.', 'On a chanté toute la soirée.', 'We sang all evening.'],
  ['danser', 'Tu veux danser ?', 'Do you want to dance?', 'Elle danse très bien.', 'She dances very well.'],
  ['rire', 'Tout le monde a ri.', 'Everybody laughed.', 'Ne me fais pas rire.', 'Don’t make me laugh.'],
  ['pleurer', 'Le bébé pleure encore.', 'The baby is crying again.', 'Il n’y a pas de quoi pleurer.', 'There’s nothing to cry about.'],
  ['sourire', 'Elle m’a souri.', 'She smiled at me.', 'Il a un beau sourire.', 'He has a lovely smile.'],
  ['crier', 'Ne crie pas, je t’entends.', 'Don’t shout, I can hear you.', 'Quelqu’un a crié dans la rue.', 'Somebody shouted in the street.'],
  ['se lever', 'Je me lève à six heures.', 'I get up at six.', 'Lève-toi, il est tard.', 'Get up, it’s late.'],
  ['se coucher', 'Je me couche tôt en semaine.', 'I go to bed early on weekdays.', 'Les enfants se couchent à huit heures.', 'The children go to bed at eight.'],
  ['se réveiller', 'Je me suis réveillé à cinq heures.', 'I woke up at five.', 'Réveille-moi à sept heures.', 'Wake me at seven.'],
  ['se dépêcher', 'Dépêche-toi, on est en retard.', 'Hurry up, we’re late.', 'Il s’est dépêché pour rien.', 'He hurried for nothing.'],
  ['s’asseoir', 'Asseyez-vous, je vous en prie.', 'Do sit down.', 'On s’assoit où ?', 'Where shall we sit?'],
  ['se souvenir', 'Je m’en souviens très bien.', 'I remember it very well.', 'Tu te souviens de lui ?', 'Do you remember him?'],
  ['s’habiller', 'Habille-toi, on part.', 'Get dressed, we’re leaving.', 'Elle s’habille toujours en noir.', 'She always dresses in black.'],
  ['se promener', 'On s’est promenés au bord de l’eau.', 'We walked along the water’s edge.', 'Je me promène souvent le dimanche.', 'I often go for a walk on Sundays.'],
  ['se tromper', 'Je me suis trompé de train.', 'I got on the wrong train.', 'Tout le monde peut se tromper.', 'Anyone can make a mistake.'],
  ['s’ennuyer', 'Je m’ennuie un peu ici.', 'I’m a bit bored here.', 'Les enfants s’ennuyaient.', 'The children were bored.'],
  ['valoir', 'Ce tableau doit valoir cher.', 'That painting must be worth a lot.', 'Il vaut mieux partir tôt.', 'It’s better to leave early.'],
  ['suffire', 'Ça suffit !', 'That’s enough!', 'Une heure suffira.', 'An hour will be enough.'],
  ['appartenir', 'Ce sac appartient à qui ?', 'Who does this bag belong to?', 'Cette maison appartenait à mes parents.', 'This house belonged to my parents.'],
  ['obtenir', 'Il a obtenu une réponse.', 'He got an answer.', 'J’aimerais obtenir un rendez-vous.', 'I’d like to get an appointment.'],
  ['retenir', 'Je n’arrive pas à retenir son nom.', 'I can’t remember his name.', 'Retiens-moi une place.', 'Save me a seat.'],
  ['contenir', 'Cette boîte contient des photos.', 'This box contains photographs.', 'Le paquet contient six œufs.', 'The packet contains six eggs.'],
  ['produire', 'Cette région produit du vin.', 'This region produces wine.', 'L’accident s’est produit hier.', 'The accident happened yesterday.'],
  ['traduire', 'Tu peux me traduire ça ?', 'Can you translate this for me?', 'Le livre a été traduit en anglais.', 'The book has been translated into English.'],
  ['détruire', 'L’orage a détruit le toit.', 'The storm destroyed the roof.', 'Ne détruis pas ces papiers.', 'Don’t destroy those papers.'],
  ['nourrir', 'Il faut nourrir le chat.', 'The cat needs feeding.', 'Ça ne nourrit pas son homme.', 'It doesn’t pay the bills.'],
  ['ouvrier', 'Les ouvriers commencent à sept heures.', 'The workmen start at seven.', 'Son père était ouvrier.', 'His father was a factory worker.'],
  ['métier', 'Quel est votre métier ?', 'What do you do for a living?', 'C’est un métier difficile.', 'It’s a hard job.'],
  ['bureau', 'Je suis au bureau jusqu’à six heures.', 'I’m at the office until six.', 'Pose-le sur mon bureau.', 'Put it on my desk.'],
  ['réunion', 'La réunion commence à dix heures.', 'The meeting starts at ten.', 'Il est en réunion.', 'He’s in a meeting.'],
  ['projet', 'On a un nouveau projet.', 'We have a new project.', 'Quels sont tes projets pour l’été ?', 'What are your plans for the summer?'],
  ['entreprise', 'Elle dirige une petite entreprise.', 'She runs a small company.', 'L’entreprise a vingt employés.', 'The company has twenty employees.'],
  ['client', 'Le client attend depuis dix minutes.', 'The customer has been waiting ten minutes.', 'Nous avons perdu un gros client.', 'We’ve lost a big client.'],
  ['patron', 'Le patron n’est pas là.', 'The boss isn’t in.', 'J’en parlerai à mon patron.', 'I’ll speak to my boss about it.'],
  ['collègue', 'Une collègue m’a prévenu.', 'A colleague let me know.', 'Mes collègues sont sympas.', 'My colleagues are nice.'],
  ['salaire', 'Le salaire est correct.', 'The pay is all right.', 'Il a demandé une augmentation de salaire.', 'He asked for a pay rise.'],
  ['cours', 'Le cours commence à neuf heures.', 'The class starts at nine.', 'Je prends des cours de français.', 'I take French lessons.'],
  ['classe', 'Il y a trente élèves dans la classe.', 'There are thirty pupils in the class.', 'Elle voyage en première classe.', 'She travels first class.'],
  ['professeur', 'Notre professeur est très patient.', 'Our teacher is very patient.', 'Elle est professeur de musique.', 'She’s a music teacher.'],
  ['élève', 'Cet élève travaille bien.', 'This pupil works hard.', 'Les élèves sont en vacances.', 'The pupils are on holiday.'],
  ['étudiant', 'Je suis étudiant en droit.', 'I’m a law student.', 'Les étudiants cherchent un logement.', 'The students are looking for somewhere to live.'],
  ['exercice', 'Fais l’exercice trois.', 'Do exercise three.', 'Cet exercice est trop long.', 'This exercise is too long.'],
  ['note', 'J’ai eu une bonne note.', 'I got a good mark.', 'Je prends des notes pendant le cours.', 'I take notes during the class.'],
  ['examen', 'L’examen est en juin.', 'The exam is in June.', 'Il a raté son examen.', 'He failed his exam.'],
  ['université', 'Elle entre à l’université en septembre.', 'She starts university in September.', 'L’université est à côté du parc.', 'The university is next to the park.'],
  ['bibliothèque', 'Je travaille à la bibliothèque.', 'I work in the library.', 'La bibliothèque ferme à dix-huit heures.', 'The library closes at six.'],
  ['corps', 'Tout le corps me fait mal.', 'My whole body aches.', 'Le corps humain est étonnant.', 'The human body is astonishing.'],
  ['tête', 'Tourne la tête vers moi.', 'Turn your head towards me.', 'Il fait la tête depuis hier.', 'He’s been sulking since yesterday.'],
  ['yeux', 'Elle a les yeux verts.', 'She has green eyes.', 'Ferme les yeux.', 'Close your eyes.'],
  ['bouche', 'Ouvrez la bouche.', 'Open your mouth.', 'Il en parle de bouche à oreille.', 'He passes it on by word of mouth.'],
  ['bras', 'Il s’est cassé le bras.', 'He broke his arm.', 'Elle portait le bébé dans ses bras.', 'She was carrying the baby in her arms.'],
  ['jambe', 'J’ai mal à la jambe.', 'My leg hurts.', 'Il a les jambes longues.', 'He has long legs.'],
  ['pied', 'On y va à pied ?', 'Shall we walk there?', 'J’ai mal aux pieds.', 'My feet hurt.'],
  ['cœur', 'Il a bon cœur.', 'He’s kind-hearted.', 'Je le sais par cœur.', 'I know it by heart.'],
  ['dos', 'J’ai mal au dos.', 'My back hurts.', 'Il est parti sans se retourner, le sac au dos.', 'He left without turning round, rucksack on his back.'],
  ['doigt', 'Je me suis coupé le doigt.', 'I’ve cut my finger.', 'Il compte sur ses doigts.', 'He counts on his fingers.'],
  ['santé', 'À votre santé !', 'Your good health!', 'Sa santé s’améliore.', 'His health is improving.'],
  ['médecin', 'Je dois voir un médecin.', 'I need to see a doctor.', 'Le médecin passe cet après-midi.', 'The doctor is coming this afternoon.'],
  ['hôpital', 'Il est resté trois jours à l’hôpital.', 'He was in hospital for three days.', 'L’hôpital est de l’autre côté de la ville.', 'The hospital is on the other side of town.'],
  ['pharmacie', 'La pharmacie est ouverte jusqu’à vingt heures.', 'The chemist’s is open until eight.', 'Il y a une pharmacie de garde.', 'There’s a duty chemist.'],
  ['médicament', 'Prenez ce médicament trois fois par jour.', 'Take this medicine three times a day.', 'Ce médicament est sans ordonnance.', 'This medicine is over the counter.'],
  ['douleur', 'La douleur est passée.', 'The pain has gone.', 'J’ai une douleur au genou.', 'I have a pain in my knee.'],
  ['fièvre', 'Il a de la fièvre.', 'He has a temperature.', 'La fièvre est tombée.', 'The fever has gone down.'],
  ['accident', 'Il y a eu un accident sur la route.', 'There’s been an accident on the road.', 'Ce n’était pas un accident.', 'It was no accident.'],
  ['urgence', 'C’est une urgence.', 'It’s an emergency.', 'Il est parti d’urgence.', 'He left in a hurry.'],
  ['sommeil', 'J’ai sommeil.', 'I’m sleepy.', 'Il manque de sommeil.', 'He isn’t getting enough sleep.'],
  ['chien', 'Le chien du voisin aboie la nuit.', 'The neighbour’s dog barks at night.', 'Je sors le chien.', 'I’m taking the dog out.'],
  ['chat', 'Le chat dort sur le lit.', 'The cat is asleep on the bed.', 'J’ai un chat dans la gorge.', 'I have a frog in my throat.'],
  ['oiseau', 'Un oiseau chante dans le jardin.', 'A bird is singing in the garden.', 'Les oiseaux partent en automne.', 'The birds leave in autumn.'],
  ['cheval', 'Elle monte à cheval le week-end.', 'She goes riding at the weekend.', 'Le cheval est dans le champ.', 'The horse is in the field.'],
  ['arbre', 'Il y a un grand arbre devant la maison.', 'There’s a big tree in front of the house.', 'Les arbres perdent leurs feuilles.', 'The trees are losing their leaves.'],
  ['fleur', 'Je lui ai offert des fleurs.', 'I gave her flowers.', 'Les fleurs sont déjà fanées.', 'The flowers have already wilted.'],
  ['herbe', 'L’herbe est encore mouillée.', 'The grass is still wet.', 'On s’est assis dans l’herbe.', 'We sat down on the grass.'],
  ['forêt', 'On s’est promenés dans la forêt.', 'We walked in the forest.', 'La forêt commence après le village.', 'The forest starts after the village.'],
  ['champ', 'Le champ est plein de fleurs.', 'The field is full of flowers.', 'Il travaille dans les champs.', 'He works in the fields.'],
  ['campagne', 'Ils habitent à la campagne.', 'They live in the country.', 'On part à la campagne ce week-end.', 'We’re off to the country this weekend.'],
  ['mer', 'On va à la mer cet été.', 'We’re going to the seaside this summer.', 'La mer est calme ce matin.', 'The sea is calm this morning.'],
  ['montagne', 'Ils passent l’hiver à la montagne.', 'They spend the winter in the mountains.', 'On voit la montagne d’ici.', 'You can see the mountain from here.'],
  ['plage', 'La plage est à dix minutes.', 'The beach is ten minutes away.', 'Il n’y avait personne sur la plage.', 'There was nobody on the beach.'],
  ['lac', 'On a fait le tour du lac.', 'We walked round the lake.', 'Le lac est gelé en janvier.', 'The lake freezes in January.'],
  ['rivière', 'La rivière passe derrière le village.', 'The river runs behind the village.', 'On s’est baignés dans la rivière.', 'We swam in the river.'],
  ['île', 'L’île est à une heure de bateau.', 'The island is an hour away by boat.', 'Ils habitent sur une petite île.', 'They live on a small island.'],
  ['ciel', 'Le ciel est gris aujourd’hui.', 'The sky is grey today.', 'Il n’y a pas un nuage dans le ciel.', 'There isn’t a cloud in the sky.'],
  ['soleil', 'Il y a du soleil ce matin.', 'It’s sunny this morning.', 'Le soleil se couche tard en juin.', 'The sun sets late in June.'],
  ['lune', 'La lune est pleine ce soir.', 'There’s a full moon tonight.', 'On voyait la lune entre les arbres.', 'You could see the moon between the trees.'],
  ['étoile', 'On voit bien les étoiles ici.', 'You can see the stars well here.', 'Il n’y a pas une étoile ce soir.', 'There isn’t a star out tonight.'],
  ['pluie', 'La pluie a duré toute la nuit.', 'The rain lasted all night.', 'On est rentrés sous la pluie.', 'We came home in the rain.'],
  ['neige', 'Il y a de la neige sur la route.', 'There’s snow on the road.', 'La neige a fondu très vite.', 'The snow melted very quickly.'],
  ['vent', 'Il y a du vent aujourd’hui.', 'It’s windy today.', 'Le vent a cassé une branche.', 'The wind broke a branch.'],
  ['orage', 'Un orage arrive.', 'A storm is coming.', 'L’orage a duré une heure.', 'The storm lasted an hour.'],
  ['nuage', 'Il n’y a pas un nuage.', 'There isn’t a cloud in sight.', 'Les nuages arrivent de l’ouest.', 'The clouds are coming in from the west.'],
  ['saison', 'C’est la meilleure saison pour venir.', 'It’s the best season to come.', 'Les fraises sont de saison.', 'Strawberries are in season.'],
  ['été', 'L’été dernier, il a fait très chaud.', 'Last summer it was very hot.', 'En été, on dîne dehors.', 'In summer we eat outside.'],
  ['hiver', 'L’hiver est long ici.', 'Winter is long here.', 'En hiver, il fait nuit à cinq heures.', 'In winter it’s dark at five.'],
  ['printemps', 'Le printemps arrive tôt cette année.', 'Spring is early this year.', 'Au printemps, le jardin est magnifique.', 'In spring the garden is beautiful.'],
  ['automne', 'En automne, les feuilles tombent.', 'In autumn the leaves fall.', 'L’automne est ma saison préférée.', 'Autumn is my favourite season.'],
  ['vêtement', 'Prends des vêtements chauds.', 'Take some warm clothes.', 'Ses vêtements sont encore mouillés.', 'His clothes are still wet.'],
  ['robe', 'Elle porte une robe rouge.', 'She’s wearing a red dress.', 'Cette robe te va bien.', 'That dress suits you.'],
  ['pantalon', 'Mon pantalon est trop grand.', 'My trousers are too big.', 'Il a acheté un pantalon noir.', 'He bought a pair of black trousers.'],
  ['chemise', 'Il a mis une chemise blanche.', 'He put on a white shirt.', 'Cette chemise a besoin d’un repassage.', 'This shirt needs ironing.'],
  ['chaussure', 'Mes chaussures sont sales.', 'My shoes are dirty.', 'Quelle est votre pointure de chaussures ?', 'What shoe size are you?'],
  ['manteau', 'Mets ton manteau.', 'Put your coat on.', 'Son manteau est resté au vestiaire.', 'His coat is still in the cloakroom.'],
  ['poche', 'J’ai les clés dans ma poche.', 'I have the keys in my pocket.', 'Ce livre tient dans une poche.', 'This book fits in a pocket.'],
  ['sac', 'Mon sac est trop lourd.', 'My bag is too heavy.', 'Elle a oublié son sac dans le train.', 'She left her bag on the train.'],
  ['valise', 'Ma valise ne ferme plus.', 'My suitcase won’t shut.', 'Je fais ma valise ce soir.', 'I’m packing tonight.'],
  ['clé', 'J’ai perdu mes clés.', 'I’ve lost my keys.', 'La clé est sous le paillasson.', 'The key is under the mat.'],
  ['couleur', 'De quelle couleur est la voiture ?', 'What colour is the car?', 'J’aime beaucoup cette couleur.', 'I really like that colour.'],
  ['blanc', 'Je prends du vin blanc.', 'I’ll have white wine.', 'Les murs sont blancs.', 'The walls are white.'],
  ['noir', 'Il porte un manteau noir.', 'He’s wearing a black coat.', 'Il fait noir dehors.', 'It’s dark outside.'],
  ['rouge', 'Le feu est rouge.', 'The light is red.', 'Une voiture rouge est garée devant.', 'A red car is parked outside.'],
  ['bleu', 'Le ciel est bleu.', 'The sky is blue.', 'Elle a les yeux bleus.', 'She has blue eyes.'],
  ['vert', 'Le feu est vert, tu peux y aller.', 'The light is green, you can go.', 'Il n’y a pas assez d’espaces verts.', 'There aren’t enough green spaces.'],
  ['jaune', 'Les feuilles deviennent jaunes.', 'The leaves are turning yellow.', 'Il a une chemise jaune.', 'He has a yellow shirt.'],
  ['taille', 'Vous faites quelle taille ?', 'What size are you?', 'Ce pull n’est pas à ma taille.', 'This jumper isn’t my size.'],
  ['poids', 'Le poids est indiqué sur le paquet.', 'The weight is marked on the packet.', 'Il a perdu du poids.', 'He’s lost weight.'],
  ['forme', 'Je suis en pleine forme.', 'I’m on great form.', 'La table a une forme bizarre.', 'The table is an odd shape.'],
  ['vin', 'Un verre de vin rouge, s’il vous plaît.', 'A glass of red wine, please.', 'Ce vin vient du sud.', 'This wine comes from the south.'],
  ['lait', 'Je prends mon café avec du lait.', 'I have milk in my coffee.', 'Il n’y a plus de lait.', 'There’s no milk left.'],
  ['fromage', 'Le fromage est excellent ici.', 'The cheese is excellent here.', 'Je prendrai du fromage après.', 'I’ll have cheese afterwards.'],
  ['viande', 'Je ne mange pas de viande.', 'I don’t eat meat.', 'La viande est trop cuite.', 'The meat is overcooked.'],
  ['poisson', 'Le poisson est très frais.', 'The fish is very fresh.', 'On mange du poisson le vendredi.', 'We eat fish on Fridays.'],
  ['légume', 'Mange tes légumes.', 'Eat your vegetables.', 'Ce plat est servi avec des légumes.', 'This dish comes with vegetables.'],
  ['fruit', 'Tu veux un fruit ?', 'Would you like a piece of fruit?', 'Les fruits sont chers en hiver.', 'Fruit is expensive in winter.'],
  ['pomme', 'Une pomme par jour, ça suffit.', 'An apple a day is enough.', 'Ces pommes viennent du jardin.', 'These apples are from the garden.'],
  ['gâteau', 'J’ai fait un gâteau.', 'I made a cake.', 'Il reste un morceau de gâteau.', 'There’s a piece of cake left.'],
  ['sucre', 'Avec ou sans sucre ?', 'With or without sugar?', 'Il ne met jamais de sucre.', 'He never takes sugar.'],
  ['restaurant', 'On va au restaurant ce soir.', 'We’re going out to eat tonight.', 'Ce restaurant est toujours plein.', 'This restaurant is always full.'],
  ['hôtel', 'L’hôtel est en face de la gare.', 'The hotel is opposite the station.', 'On a réservé deux nuits à l’hôtel.', 'We’ve booked two nights at the hotel.'],
  ['menu', 'Je prends le menu du jour.', 'I’ll have the set menu.', 'Le menu change chaque semaine.', 'The menu changes every week.'],
  ['addition', 'L’addition, s’il vous plaît.', 'The bill, please.', 'On partage l’addition ?', 'Shall we split the bill?'],
  ['cuisinier', 'Le cuisinier est italien.', 'The chef is Italian.', 'Mon frère est cuisinier.', 'My brother is a cook.'],
  ['serveur', 'Le serveur arrive tout de suite.', 'The waiter is coming right away.', 'J’ai demandé au serveur.', 'I asked the waiter.'],
  ['verre', 'Un verre d’eau, s’il vous plaît.', 'A glass of water, please.', 'On prend un verre après le travail ?', 'Shall we have a drink after work?'],
  ['assiette', 'Ton assiette est encore pleine.', 'Your plate is still full.', 'Il a mis les assiettes sur la table.', 'He put the plates on the table.'],
  ['couteau', 'Il manque un couteau.', 'There’s a knife missing.', 'Ce couteau ne coupe pas.', 'This knife doesn’t cut.'],
  ['bouteille', 'Une bouteille d’eau, s’il vous plaît.', 'A bottle of water, please.', 'La bouteille est vide.', 'The bottle is empty.'],
  ['téléphone', 'Mon téléphone n’a plus de batterie.', 'My phone is out of battery.', 'Il est au téléphone.', 'He’s on the phone.'],
  ['ordinateur', 'Mon ordinateur est lent.', 'My computer is slow.', 'Elle travaille sur son ordinateur.', 'She’s working on her computer.'],
  ['message', 'Je t’ai laissé un message.', 'I left you a message.', 'Il n’a pas répondu à mon message.', 'He hasn’t answered my message.'],
  ['journal', 'Je lis le journal le matin.', 'I read the paper in the morning.', 'C’était dans le journal d’hier.', 'It was in yesterday’s paper.'],
  ['nouvelle', 'J’ai une bonne nouvelle.', 'I have some good news.', 'Tu as des nouvelles de ta sœur ?', 'Have you heard from your sister?'],
  ['musique', 'Baisse la musique, s’il te plaît.', 'Turn the music down, please.', 'Elle écoute de la musique en travaillant.', 'She listens to music while she works.'],
  ['film', 'Le film dure deux heures.', 'The film is two hours long.', 'On a vu un très bon film.', 'We saw a very good film.'],
  ['photo', 'Je peux prendre une photo ?', 'May I take a photo?', 'Cette photo est floue.', 'This photo is blurred.'],
  ['jeu', 'C’est un jeu d’enfant.', 'It’s child’s play.', 'Les enfants ont inventé un jeu.', 'The children made up a game.'],
  ['sport', 'Tu fais du sport ?', 'Do you do any sport?', 'Le sport lui fait du bien.', 'Sport does him good.'],
  ['avion', 'L’avion décolle à midi.', 'The plane takes off at midday.', 'Je n’aime pas prendre l’avion.', 'I don’t like flying.'],
  ['bus', 'Le bus passe toutes les dix minutes.', 'The bus comes every ten minutes.', 'J’ai raté le dernier bus.', 'I missed the last bus.'],
  ['vélo', 'Je vais au travail à vélo.', 'I cycle to work.', 'Son vélo a un pneu crevé.', 'His bike has a flat tyre.'],
  ['bateau', 'On prend le bateau à huit heures.', 'We take the boat at eight.', 'Le bateau part du vieux port.', 'The boat leaves from the old harbour.'],
  ['aéroport', 'L’aéroport est loin du centre.', 'The airport is a long way from the centre.', 'Je vous emmène à l’aéroport.', 'I’ll take you to the airport.'],
  ['voyage', 'Bon voyage !', 'Have a good trip!', 'Le voyage a duré six heures.', 'The journey took six hours.'],
  ['vacances', 'Je suis en vacances la semaine prochaine.', 'I’m on holiday next week.', 'Bonnes vacances !', 'Have a good holiday!'],
  ['hôte', 'Nos hôtes sont très accueillants.', 'Our hosts are very welcoming.', 'Le maître de maison reçoit ses hôtes.', 'The host is receiving his guests.'],
  ['frontière', 'On a passé la frontière à midi.', 'We crossed the border at midday.', 'Le village est près de la frontière.', 'The village is near the border.'],
  ['passeport', 'Votre passeport, s’il vous plaît.', 'Your passport, please.', 'Mon passeport est périmé.', 'My passport has expired.'],
  ['centre', 'Le centre est fermé aux voitures.', 'The centre is closed to cars.', 'On se retrouve au centre-ville.', 'Let’s meet in the town centre.'],
  ['village', 'Le village compte trois cents habitants.', 'The village has three hundred inhabitants.', 'Il n’y a qu’un café dans le village.', 'There’s only one café in the village.'],
  ['quartier', 'C’est un quartier tranquille.', 'It’s a quiet area.', 'Je connais bien ce quartier.', 'I know this part of town well.'],
  ['immeuble', 'Leur immeuble date des années trente.', 'Their block dates from the thirties.', 'Il y a des travaux dans l’immeuble.', 'There’s building work going on in the block.'],
  ['appartement', 'Mon appartement est petit mais clair.', 'My flat is small but light.', 'Ils cherchent un appartement à louer.', 'They’re looking for a flat to rent.'],
  ['étage', 'J’habite au troisième étage.', 'I live on the third floor.', 'Le bureau est à l’étage.', 'The office is upstairs.'],
  ['ascenseur', 'L’ascenseur est en panne.', 'The lift is out of order.', 'Prenez l’ascenseur jusqu’au cinquième.', 'Take the lift to the fifth floor.'],
  ['escalier', 'Je monte par l’escalier.', 'I’ll take the stairs.', 'L’escalier est raide.', 'The staircase is steep.'],
  ['mur', 'Le tableau est au mur.', 'The picture is on the wall.', 'Les murs sont très fins.', 'The walls are very thin.'],
  ['toit', 'Le toit fuit depuis l’orage.', 'The roof has leaked since the storm.', 'On voit la mer depuis le toit.', 'You can see the sea from the roof.'],
  ['police', 'Appelez la police.', 'Call the police.', 'La police est arrivée très vite.', 'The police arrived very quickly.'],
  ['loi', 'C’est la loi.', 'It’s the law.', 'La nouvelle loi entre en vigueur en janvier.', 'The new law comes into force in January.'],
  ['guerre', 'Son grand-père a fait la guerre.', 'His grandfather fought in the war.', 'La guerre a duré quatre ans.', 'The war lasted four years.'],
  ['paix', 'Laisse-moi en paix.', 'Leave me in peace.', 'Ils ont signé la paix.', 'They made peace.'],
  ['peuple', 'Le peuple a voté.', 'The people voted.', 'C’est un peuple accueillant.', 'They’re a welcoming people.'],
  ['roi', 'Le roi est mort en 1715.', 'The king died in 1715.', 'On se croirait chez un roi.', 'It’s fit for a king.'],
  ['président', 'Le président parle à la télévision ce soir.', 'The president is on television tonight.', 'Elle est présidente de l’association.', 'She’s chair of the association.'],
  ['élection', 'Les élections ont lieu en mai.', 'The elections are in May.', 'Il a perdu l’élection de peu.', 'He narrowly lost the election.'],
  ['impôt', 'Les impôts augmentent cette année.', 'Taxes are going up this year.', 'Il faut déclarer ses impôts en avril.', 'You have to file your tax return in April.'],
  ['liberté', 'La liberté n’a pas de prix.', 'Freedom is priceless.', 'Il a retrouvé sa liberté.', 'He got his freedom back.'],
  ['amour', 'C’est une histoire d’amour.', 'It’s a love story.', 'Il fait ça par amour du métier.', 'He does it for the love of the job.'],
  ['peur', 'N’aie pas peur.', 'Don’t be afraid.', 'J’ai eu peur pour rien.', 'I was frightened over nothing.'],
  ['joie', 'Quelle joie de te voir !', 'What a joy to see you!', 'Elle a accepté avec joie.', 'She was delighted to accept.'],
  ['colère', 'Il est en colère contre moi.', 'He’s angry with me.', 'Sa colère est passée.', 'His anger has blown over.'],
  ['espoir', 'Il reste un espoir.', 'There’s still hope.', 'Ne perds pas espoir.', 'Don’t lose hope.'],
  ['chance', 'Bonne chance !', 'Good luck!', 'Tu as de la chance.', 'You’re lucky.'],
  ['vérité', 'Dis-moi la vérité.', 'Tell me the truth.', 'La vérité finit toujours par sortir.', 'The truth always comes out in the end.'],
  ['mensonge', 'C’est un mensonge.', 'That’s a lie.', 'Ses mensonges ont fini par se voir.', 'His lies ended up showing.'],
  ['secret', 'Garde-le pour toi, c’est un secret.', 'Keep it to yourself, it’s a secret.', 'Il n’y a pas de secret : il travaille.', 'There’s no secret to it: he works.'],
  ['souvenir', 'J’en garde un bon souvenir.', 'I have fond memories of it.', 'Il m’a rapporté un souvenir de Rome.', 'He brought me back a souvenir from Rome.'],
  ['début', 'Au début, c’était difficile.', 'At the start it was hard.', 'On se voit début juin.', 'We’ll meet at the beginning of June.'],
  ['fin', 'Je pars à la fin du mois.', 'I’m leaving at the end of the month.', 'La fin du film est surprenante.', 'The end of the film is surprising.'],
  ['milieu', 'Il s’est réveillé au milieu de la nuit.', 'He woke up in the middle of the night.', 'Mets la lampe au milieu de la table.', 'Put the lamp in the middle of the table.'],
  ['côté', 'La banque est de l’autre côté.', 'The bank is on the other side.', 'Mets-toi à côté de moi.', 'Sit next to me.'],
  ['bout', 'C’est au bout de la rue.', 'It’s at the end of the street.', 'J’ai lu le livre jusqu’au bout.', 'I read the book right through.'],
  ['part', 'Tu veux une part de gâteau ?', 'Would you like a slice of cake?', 'De ma part, dis-lui bonjour.', 'Say hello to him from me.'],
  ['moitié', 'J’ai fait la moitié du travail.', 'I’ve done half the work.', 'La moitié des places sont libres.', 'Half the seats are free.'],
  ['nombre', 'Le nombre de visiteurs augmente.', 'The number of visitors is rising.', 'Ils sont venus en grand nombre.', 'They came in large numbers.'],
  ['numéro', 'Tu as son numéro ?', 'Do you have his number?', 'J’habite au numéro douze.', 'I live at number twelve.'],
  ['reste', 'Le reste est pour toi.', 'The rest is for you.', 'On verra le reste demain.', 'We’ll look at the rest tomorrow.'],
  ['avis', 'À mon avis, c’est trop tard.', 'In my opinion it’s too late.', 'Elle a changé d’avis.', 'She changed her mind.'],
  ['choix', 'Tu as le choix.', 'You have a choice.', 'Ce n’était pas un choix facile.', 'It wasn’t an easy choice.'],
  ['façon', 'De toute façon, il est trop tard.', 'In any case it’s too late.', 'Il le fait à sa façon.', 'He does it his own way.'],
  ['manière', 'Il y a une meilleure manière de le dire.', 'There’s a better way of putting it.', 'De cette manière, tout est clair.', 'That way, everything is clear.'],
  ['groupe', 'On part en groupe.', 'We’re going as a group.', 'Le groupe se retrouve devant l’entrée.', 'The group is meeting at the entrance.'],
  ['ordre', 'Tout est en ordre.', 'Everything is in order.', 'Rangez les fiches par ordre alphabétique.', 'Put the cards in alphabetical order.'],
  ['sens', 'Ça n’a aucun sens.', 'That makes no sense.', 'Vous allez dans le mauvais sens.', 'You’re going the wrong way.'],
  ['effort', 'Fais un effort.', 'Make an effort.', 'Ses efforts ont payé.', 'His efforts paid off.'],
  ['besoin', 'J’ai besoin de toi.', 'I need you.', 'Il n’y a pas besoin de réserver.', 'There’s no need to book.'],
  ['envie', 'J’ai envie d’un café.', 'I fancy a coffee.', 'Elle n’avait pas envie de sortir.', 'She didn’t feel like going out.'],
  ['joli', 'C’est un joli village.', 'It’s a pretty village.', 'Elle a une jolie voix.', 'She has a lovely voice.'],
  ['propre', 'La chambre est propre.', 'The room is clean.', 'Il a sa propre voiture.', 'He has his own car.'],
  ['sale', 'Mes mains sont sales.', 'My hands are dirty.', 'Il a fait un sale temps.', 'The weather has been foul.'],
  ['gratuit', 'L’entrée est gratuite le dimanche.', 'Entry is free on Sundays.', 'Rien n’est jamais gratuit.', 'Nothing is ever free.'],
  ['simple', 'C’est plus simple qu’il n’y paraît.', 'It’s simpler than it looks.', 'Un aller simple, s’il vous plaît.', 'A single ticket, please.'],
  ['compliqué', 'C’est trop compliqué pour moi.', 'It’s too complicated for me.', 'Ne complique pas les choses.', 'Don’t make things complicated.'],
  ['utile', 'Ce conseil m’a été très utile.', 'That advice was very useful to me.', 'Est-ce que je peux me rendre utile ?', 'Can I make myself useful?'],
  ['inutile', 'C’est inutile d’insister.', 'There’s no point insisting.', 'Il a fait le voyage pour rien.', 'He made the journey for nothing.'],
  ['impossible', 'C’est impossible à lire.', 'It’s impossible to read.', 'Rien n’est impossible.', 'Nothing is impossible.'],
  ['vide', 'Le réservoir est vide.', 'The tank is empty.', 'La salle était à moitié vide.', 'The room was half empty.'],
  ['lourd', 'Ce sac est trop lourd.', 'This bag is too heavy.', 'Il fait lourd aujourd’hui.', 'It’s muggy today.'],
  ['léger', 'Prends un manteau léger.', 'Take a light coat.', 'J’ai le sommeil léger.', 'I’m a light sleeper.'],
  ['rapide', 'C’est le chemin le plus rapide.', 'It’s the quickest way.', 'Une réponse rapide serait utile.', 'A quick answer would help.'],
  ['lent', 'La connexion est très lente.', 'The connection is very slow.', 'Il marche d’un pas lent.', 'He walks slowly.'],
  ['haut', 'Le mur est trop haut.', 'The wall is too high.', 'Parlez plus haut, s’il vous plaît.', 'Speak up, please.'],
  ['bas', 'Il parle à voix basse.', 'He speaks quietly.', 'Les prix sont plus bas en ligne.', 'Prices are lower online.'],
  ['proche', 'La gare est toute proche.', 'The station is very close.', 'C’est un ami proche.', 'He’s a close friend.'],
  ['loin', 'Ce n’est pas loin d’ici.', 'It isn’t far from here.', 'Il habite trop loin du travail.', 'He lives too far from work.'],
  ['doux', 'Il fait doux ce matin.', 'It’s mild this morning.', 'Elle a une voix douce.', 'She has a gentle voice.'],
  ['dur', 'Le pain est dur.', 'The bread is hard.', 'C’est dur de se lever tôt.', 'It’s hard getting up early.'],
  ['meilleur', 'C’est le meilleur restaurant du quartier.', 'It’s the best restaurant in the area.', 'Tous mes meilleurs vœux.', 'All my best wishes.'],
  ['pire', 'C’est pire qu’hier.', 'It’s worse than yesterday.', 'Le pire est passé.', 'The worst is over.'],
  ['entier', 'Il a mangé le gâteau entier.', 'He ate the whole cake.', 'Le monde entier le sait.', 'The whole world knows.'],
  ['clair', 'Sa réponse était très claire.', 'His answer was very clear.', 'La chambre est claire le matin.', 'The room is light in the morning.'],
  ['sombre', 'La pièce est un peu sombre.', 'The room is a bit dark.', 'Il portait un costume sombre.', 'He was wearing a dark suit.'],
  ['calme', 'Reste calme.', 'Stay calm.', 'C’est un quartier calme le soir.', 'It’s a quiet area in the evening.'],
  ['bruyant', 'Les voisins sont bruyants.', 'The neighbours are noisy.', 'Le café était trop bruyant pour parler.', 'The café was too noisy to talk in.'],
  ['sérieux', 'Tu es sérieux ?', 'Are you serious?', 'C’est un problème sérieux.', 'It’s a serious problem.'],
  ['célèbre', 'Ce peintre est très célèbre ici.', 'This painter is very famous here.', 'Le village est célèbre pour son marché.', 'The village is famous for its market.'],
  ['pauvre', 'Le pauvre, il a tout raté.', 'Poor thing, he missed everything.', 'La région est pauvre mais belle.', 'The region is poor but beautiful.'],
];

const slug = (value) => value.normalize('NFD').replace(/[̀-ͯ]/g, '')
  .toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

const RANK = new Map(WORDS.map((word, i) => [word, i]));

const bandOf = (rank) => BANDS.find((band) => rank >= band.from && rank < band.to).id;

/** Two sentences per row, each a card of its own. */
export const SENTENCES = RAW.flatMap(([word, ...pairs]) => {
  const rank = RANK.get(word);
  if (rank === undefined) throw new Error(`not in the word list: ${word}`);
  return [0, 2].map((i) => ({
    word,
    rank,
    band: bandOf(rank),
    fr: pairs[i],
    en: pairs[i + 1],
    id: slug(pairs[i]),
  }));
});

export const SENTENCE_BY_ID = new Map(SENTENCES.map((sentence) => [sentence.id, sentence]));

export const sentencesForBands = (bands) =>
  SENTENCES.filter((sentence) => bands.includes(sentence.band));
