/**
 * A thousand French words, with their genders.
 *
 * The sentences deck teaches words by meeting them in use. This one is the
 * blunt instrument: the word, what it means, and — the part that actually
 * costs marks — whether it is *le* or *la*.
 *
 * Gender is not decoration here. A noun learnt without its article is a
 * noun half learnt, so the French side of every noun card carries the
 * article, and typing the bare word is marked as a near miss rather than
 * waved through. Adjectives carry their feminine in brackets where it
 * differs: grand (grande), heureux (heureuse), and nothing after rouge,
 * which does not change.
 *
 * Each row is [word, meaning, kind, extra]:
 *
 *   'n'  a noun      — extra is 'm', 'f', 'mf' for either, 'f-pl' for a
 *                      noun that only exists in the plural
 *   'a'  an adjective — extra is the feminine form, or absent when the word
 *                      is the same in both
 *   'v'  a verb       — the infinitive, no extra
 *   'x'  everything else: adverbs, prepositions, conjunctions
 *
 * The articles le/la/un/une are not in the list. A card whose answer is
 * "the" teaches nothing, and they turn up in every other card anyway.
 */

export const BANDS = [
  { id: 'core', label: 'First 250', hint: 'the unavoidable ones', from: 0, to: 250 },
  { id: 'more', label: 'Next 350', hint: 'everyday vocabulary', from: 250, to: 600 },
  { id: 'rest', label: 'The last 400', hint: 'widening out', from: 600, to: 1000 },
];

export const KINDS = [
  { id: 'n', label: 'Nouns', hint: 'with their gender' },
  { id: 'v', label: 'Verbs', hint: 'infinitives' },
  { id: 'a', label: 'Adjectives', hint: 'with the feminine' },
  { id: 'x', label: 'The rest', hint: 'adverbs and connectors' },
];

/**
 * Words beginning with h where the article does *not* elide: le hasard, not
 * l'hasard. Most h in the common thousand is mute — l'homme, l'heure,
 * l'hôtel — so the exceptions are listed rather than the rule.
 */
const ASPIRATED = new Set([
  'hasard', 'haut', 'hauteur', 'héros', 'honte', 'haine', 'hall', 'hanche',
  'harcèlement', 'hibou', 'hockey', 'homard', 'honte', 'hors-d’œuvre', 'housse',
]);

const RAW = [
  ['être', 'to be', 'v'],
  ['avoir', 'to have', 'v'],
  ['faire', 'to do, to make', 'v'],
  ['dire', 'to say, to tell', 'v'],
  ['aller', 'to go', 'v'],
  ['voir', 'to see', 'v'],
  ['savoir', 'to know', 'v'],
  ['pouvoir', 'to be able to, can', 'v'],
  ['vouloir', 'to want', 'v'],
  ['venir', 'to come', 'v'],
  ['devoir', 'to have to, must', 'v'],
  ['falloir', 'to be necessary', 'v'],
  ['croire', 'to believe, to think', 'v'],
  ['trouver', 'to find', 'v'],
  ['donner', 'to give', 'v'],
  ['prendre', 'to take', 'v'],
  ['parler', 'to speak', 'v'],
  ['aimer', 'to like, to love', 'v'],
  ['passer', 'to pass, to spend time', 'v'],
  ['mettre', 'to put', 'v'],
  ['demander', 'to ask', 'v'],
  ['tenir', 'to hold', 'v'],
  ['sembler', 'to seem', 'v'],
  ['laisser', 'to leave, to let', 'v'],
  ['rester', 'to stay', 'v'],
  ['penser', 'to think', 'v'],
  ['entendre', 'to hear', 'v'],
  ['regarder', 'to watch, to look at', 'v'],
  ['répondre', 'to answer', 'v'],
  ['connaître', 'to know someone, to be familiar with', 'v'],
  ['arriver', 'to arrive, to happen', 'v'],
  ['attendre', 'to wait, to expect', 'v'],
  ['vivre', 'to live', 'v'],
  ['chercher', 'to look for', 'v'],
  ['sortir', 'to go out', 'v'],
  ['comprendre', 'to understand', 'v'],
  ['porter', 'to carry, to wear', 'v'],
  ['devenir', 'to become', 'v'],
  ['entrer', 'to come in', 'v'],
  ['écrire', 'to write', 'v'],
  ['appeler', 'to call, to phone', 'v'],
  ['tomber', 'to fall', 'v'],
  ['suivre', 'to follow', 'v'],
  ['commencer', 'to begin', 'v'],
  ['jouer', 'to play', 'v'],
  ['perdre', 'to lose', 'v'],
  ['apprendre', 'to learn', 'v'],
  ['oublier', 'to forget', 'v'],
  ['travailler', 'to work', 'v'],
  ['manger', 'to eat', 'v'],
  ['temps', 'time, weather', 'n', 'm'],
  ['jour', 'day', 'n', 'm'],
  ['homme', 'man', 'n', 'm'],
  ['femme', 'woman, wife', 'n', 'f'],
  ['enfant', 'child', 'n', 'mf'],
  ['chose', 'thing', 'n', 'f'],
  ['vie', 'life', 'n', 'f'],
  ['monde', 'world, people', 'n', 'm'],
  ['pays', 'country', 'n', 'm'],
  ['ville', 'town, city', 'n', 'f'],
  ['maison', 'house', 'n', 'f'],
  ['eau', 'water', 'n', 'f'],
  ['main', 'hand', 'n', 'f'],
  ['nuit', 'night', 'n', 'f'],
  ['matin', 'morning', 'n', 'm'],
  ['soir', 'evening', 'n', 'm'],
  ['année', 'year', 'n', 'f'],
  ['an', 'year', 'n', 'm'],
  ['mois', 'month', 'n', 'm'],
  ['semaine', 'week', 'n', 'f'],
  ['heure', 'hour, time of day', 'n', 'f'],
  ['minute', 'minute', 'n', 'f'],
  ['moment', 'moment', 'n', 'm'],
  ['fois', 'time, occasion', 'n', 'f'],
  ['ami', 'friend', 'n', 'm'],
  ['gens', 'people', 'n', 'm-pl'],
  ['personne', 'person', 'n', 'f'],
  ['nom', 'name', 'n', 'm'],
  ['mot', 'word', 'n', 'm'],
  ['question', 'question', 'n', 'f'],
  ['raison', 'reason', 'n', 'f'],
  ['histoire', 'story, history', 'n', 'f'],
  ['part', 'share, part', 'n', 'f'],
  ['place', 'seat, square, room', 'n', 'f'],
  ['point', 'point, dot', 'n', 'm'],
  ['fin', 'end', 'n', 'f'],
  ['tête', 'head', 'n', 'f'],
  ['œil', 'eye', 'n', 'm'],
  ['pied', 'foot', 'n', 'm'],
  ['cœur', 'heart', 'n', 'm'],
  ['corps', 'body', 'n', 'm'],
  ['porte', 'door', 'n', 'f'],
  ['travail', 'work, job', 'n', 'm'],
  ['argent', 'money, silver', 'n', 'm'],
  ['père', 'father', 'n', 'm'],
  ['mère', 'mother', 'n', 'f'],
  ['fils', 'son', 'n', 'm'],
  ['fille', 'girl, daughter', 'n', 'f'],
  ['grand', 'big, tall', 'a', 'grande'],
  ['petit', 'small', 'a', 'petite'],
  ['bon', 'good', 'a', 'bonne'],
  ['mauvais', 'bad', 'a', 'mauvaise'],
  ['nouveau', 'new', 'a', 'nouvelle'],
  ['vieux', 'old', 'a', 'vieille'],
  ['jeune', 'young', 'a'],
  ['beau', 'beautiful', 'a', 'belle'],
  ['premier', 'first', 'a', 'première'],
  ['dernier', 'last', 'a', 'dernière'],
  ['même', 'same', 'a'],
  ['autre', 'other', 'a'],
  ['seul', 'alone, only', 'a', 'seule'],
  ['long', 'long', 'a', 'longue'],
  ['gros', 'big, fat', 'a', 'grosse'],
  ['vrai', 'true', 'a', 'vraie'],
  ['faux', 'false, wrong', 'a', 'fausse'],
  ['cher', 'expensive, dear', 'a', 'chère'],
  ['fort', 'strong, loud', 'a', 'forte'],
  ['plein', 'full', 'a', 'pleine'],
  ['blanc', 'white', 'a', 'blanche'],
  ['noir', 'black', 'a', 'noire'],
  ['bien', 'well', 'x'],
  ['très', 'very', 'x'],
  ['trop', 'too, too much', 'x'],
  ['toujours', 'always, still', 'x'],
  ['jamais', 'never', 'x'],
  ['encore', 'again, still', 'x'],
  ['déjà', 'already', 'x'],
  ['souvent', 'often', 'x'],
  ['maintenant', 'now', 'x'],
  ['peut-être', 'maybe', 'x'],
  ['aussi', 'also, too', 'x'],
  ['alors', 'then, so', 'x'],
  ['donc', 'so, therefore', 'x'],
  ['puis', 'then', 'x'],
  ['enfin', 'at last, finally', 'x'],
  ['ici', 'here', 'x'],
  ['là', 'there', 'x'],
  ['partout', 'everywhere', 'x'],
  ['ailleurs', 'elsewhere', 'x'],
  ['dedans', 'inside', 'x'],
  ['dehors', 'outside', 'x'],
  ['dessus', 'on top', 'x'],
  ['dessous', 'underneath', 'x'],
  ['devant', 'in front of', 'x'],
  ['derrière', 'behind', 'x'],
  ['entre', 'between', 'x'],
  ['contre', 'against', 'x'],
  ['vers', 'towards, around', 'x'],
  ['chez', 'at the home of', 'x'],
  ['sans', 'without', 'x'],
  ['sous', 'under', 'x'],
  ['pendant', 'during', 'x'],
  ['depuis', 'since, for', 'x'],
  ['avant', 'before', 'x'],
  ['après', 'after', 'x'],
  ['quand', 'when', 'x'],
  ['comme', 'like, as, since', 'x'],
  ['combien', 'how much, how many', 'x'],
  ['pourquoi', 'why', 'x'],
  ['comment', 'how', 'x'],
  ['où', 'where', 'x'],
  ['beaucoup', 'a lot', 'x'],
  ['peu', 'little, few', 'x'],
  ['assez', 'enough, quite', 'x'],
  ['plus', 'more', 'x'],
  ['moins', 'less', 'x'],
  ['mieux', 'better', 'x'],
  ['mal', 'badly', 'x'],
  ['vite', 'quickly', 'x'],
  ['tard', 'late', 'x'],
  ['tôt', 'early', 'x'],
  ['hier', 'yesterday', 'x'],
  ['demain', 'tomorrow', 'x'],
  ['aujourd’hui', 'today', 'x'],
  ['ensemble', 'together', 'x'],
  ['surtout', 'above all, especially', 'x'],
  ['vraiment', 'really', 'x'],
  ['presque', 'almost', 'x'],
  ['parfois', 'sometimes', 'x'],
  ['bientôt', 'soon', 'x'],
  ['rendre', 'to give back, to make', 'v'],
  ['paraître', 'to appear, to seem', 'v'],
  ['sentir', 'to feel, to smell', 'v'],
  ['revenir', 'to come back', 'v'],
  ['monter', 'to go up', 'v'],
  ['descendre', 'to go down', 'v'],
  ['ouvrir', 'to open', 'v'],
  ['fermer', 'to close', 'v'],
  ['lire', 'to read', 'v'],
  ['boire', 'to drink', 'v'],
  ['dormir', 'to sleep', 'v'],
  ['courir', 'to run', 'v'],
  ['partir', 'to leave', 'v'],
  ['marcher', 'to walk, to work', 'v'],
  ['arrêter', 'to stop, to arrest', 'v'],
  ['choisir', 'to choose', 'v'],
  ['finir', 'to finish', 'v'],
  ['réussir', 'to succeed, to pass', 'v'],
  ['essayer', 'to try', 'v'],
  ['expliquer', 'to explain', 'v'],
  ['décider', 'to decide', 'v'],
  ['préférer', 'to prefer', 'v'],
  ['acheter', 'to buy', 'v'],
  ['payer', 'to pay', 'v'],
  ['coûter', 'to cost', 'v'],
  ['changer', 'to change', 'v'],
  ['garder', 'to keep', 'v'],
  ['montrer', 'to show', 'v'],
  ['continuer', 'to continue', 'v'],
  ['aider', 'to help', 'v'],
  ['habiter', 'to live somewhere', 'v'],
  ['rencontrer', 'to meet', 'v'],
  ['inviter', 'to invite', 'v'],
  ['envoyer', 'to send', 'v'],
  ['recevoir', 'to receive', 'v'],
  ['offrir', 'to offer, to give a present', 'v'],
  ['servir', 'to serve', 'v'],
  ['plaire', 'to please', 'v'],
  ['manquer', 'to miss, to be lacking', 'v'],
  ['rappeler', 'to call back, to remind', 'v'],
  ['permettre', 'to allow', 'v'],
  ['compter', 'to count', 'v'],
  ['gagner', 'to win, to earn', 'v'],
  ['utiliser', 'to use', 'v'],
  ['ajouter', 'to add', 'v'],
  ['apporter', 'to bring', 'v'],
  ['conduire', 'to drive', 'v'],
  ['construire', 'to build', 'v'],
  ['réfléchir', 'to think it over', 'v'],
  ['remercier', 'to thank', 'v'],
  ['remarquer', 'to notice', 'v'],
  ['rêver', 'to dream', 'v'],
  ['chanter', 'to sing', 'v'],
  ['danser', 'to dance', 'v'],
  ['rire', 'to laugh', 'v'],
  ['pleurer', 'to cry', 'v'],
  ['sourire', 'to smile', 'v'],
  ['crier', 'to shout', 'v'],
  ['valoir', 'to be worth', 'v'],
  ['suffire', 'to be enough', 'v'],
  ['obtenir', 'to obtain', 'v'],
  ['retenir', 'to hold back, to remember', 'v'],
  ['contenir', 'to contain', 'v'],
  ['produire', 'to produce', 'v'],
  ['traduire', 'to translate', 'v'],
  ['détruire', 'to destroy', 'v'],
  ['ouvrier', 'workman', 'n', 'm'],
  ['métier', 'job, trade', 'n', 'm'],
  ['bureau', 'office, desk', 'n', 'm'],
  ['réunion', 'meeting', 'n', 'f'],
  ['projet', 'project, plan', 'n', 'm'],
  ['entreprise', 'company', 'n', 'f'],
  ['client', 'customer', 'n', 'm'],
  ['patron', 'boss', 'n', 'm'],
  ['collègue', 'colleague', 'n', 'mf'],
  ['salaire', 'salary', 'n', 'm'],
  ['cours', 'class, course', 'n', 'm'],
  ['classe', 'class, classroom', 'n', 'f'],
  ['professeur', 'teacher', 'n', 'm'],
  ['élève', 'pupil', 'n', 'mf'],
  ['étudiant', 'student', 'n', 'm'],
  ['exercice', 'exercise', 'n', 'm'],
  ['note', 'mark, note', 'n', 'f'],
  ['examen', 'exam', 'n', 'm'],
  ['université', 'university', 'n', 'f'],
  ['bibliothèque', 'library', 'n', 'f'],
  ['école', 'school', 'n', 'f'],
  ['livre', 'book', 'n', 'm'],
  ['lettre', 'letter', 'n', 'f'],
  ['réponse', 'answer', 'n', 'f'],
  ['problème', 'problem', 'n', 'm'],
  ['idée', 'idea', 'n', 'f'],
  ['exemple', 'example', 'n', 'm'],
  ['page', 'page', 'n', 'f'],
  ['famille', 'family', 'n', 'f'],
  ['frère', 'brother', 'n', 'm'],
  ['sœur', 'sister', 'n', 'f'],
  ['parents', 'parents', 'n', 'm-pl'],
  ['voisin', 'neighbour', 'n', 'm'],
  ['mari', 'husband', 'n', 'm'],
  ['époux', 'spouse', 'n', 'm'],
  ['bébé', 'baby', 'n', 'm'],
  ['garçon', 'boy', 'n', 'm'],
  ['monsieur', 'sir, gentleman', 'n', 'm'],
  ['madame', 'madam, lady', 'n', 'f'],
  ['bras', 'arm', 'n', 'm'],
  ['jambe', 'leg', 'n', 'f'],
  ['dos', 'back', 'n', 'm'],
  ['doigt', 'finger', 'n', 'm'],
  ['bouche', 'mouth', 'n', 'f'],
  ['nez', 'nose', 'n', 'm'],
  ['oreille', 'ear', 'n', 'f'],
  ['cheveu', 'hair', 'n', 'm'],
  ['visage', 'face', 'n', 'm'],
  ['santé', 'health', 'n', 'f'],
  ['médecin', 'doctor', 'n', 'm'],
  ['hôpital', 'hospital', 'n', 'm'],
  ['pharmacie', 'chemist’s', 'n', 'f'],
  ['médicament', 'medicine', 'n', 'm'],
  ['douleur', 'pain', 'n', 'f'],
  ['fièvre', 'fever', 'n', 'f'],
  ['accident', 'accident', 'n', 'm'],
  ['sommeil', 'sleep', 'n', 'm'],
  ['rue', 'street', 'n', 'f'],
  ['route', 'road', 'n', 'f'],
  ['chemin', 'path, way', 'n', 'm'],
  ['voiture', 'car', 'n', 'f'],
  ['train', 'train', 'n', 'm'],
  ['gare', 'station', 'n', 'f'],
  ['billet', 'ticket', 'n', 'm'],
  ['avion', 'plane', 'n', 'm'],
  ['bus', 'bus', 'n', 'm'],
  ['vélo', 'bike', 'n', 'm'],
  ['bateau', 'boat', 'n', 'm'],
  ['aéroport', 'airport', 'n', 'm'],
  ['voyage', 'journey', 'n', 'm'],
  ['vacances', 'holiday', 'n', 'f-pl'],
  ['valise', 'suitcase', 'n', 'f'],
  ['clé', 'key', 'n', 'f'],
  ['sac', 'bag', 'n', 'm'],
  ['magasin', 'shop', 'n', 'm'],
  ['marché', 'market', 'n', 'm'],
  ['prix', 'price, prize', 'n', 'm'],
  ['euro', 'euro', 'n', 'm'],
  ['carte', 'card, map, menu', 'n', 'f'],
  ['chambre', 'bedroom', 'n', 'f'],
  ['cuisine', 'kitchen, cooking', 'n', 'f'],
  ['salle', 'room, hall', 'n', 'f'],
  ['fenêtre', 'window', 'n', 'f'],
  ['table', 'table', 'n', 'f'],
  ['chaise', 'chair', 'n', 'f'],
  ['lit', 'bed', 'n', 'm'],
  ['mur', 'wall', 'n', 'm'],
  ['toit', 'roof', 'n', 'm'],
  ['jardin', 'garden', 'n', 'm'],
  ['immeuble', 'block of flats', 'n', 'm'],
  ['appartement', 'flat', 'n', 'm'],
  ['étage', 'floor, storey', 'n', 'm'],
  ['escalier', 'staircase', 'n', 'm'],
  ['ascenseur', 'lift', 'n', 'm'],
  ['quartier', 'neighbourhood', 'n', 'm'],
  ['village', 'village', 'n', 'm'],
  ['centre', 'centre', 'n', 'm'],
  ['pain', 'bread', 'n', 'm'],
  ['café', 'coffee, café', 'n', 'm'],
  ['vin', 'wine', 'n', 'm'],
  ['lait', 'milk', 'n', 'm'],
  ['fromage', 'cheese', 'n', 'm'],
  ['viande', 'meat', 'n', 'f'],
  ['poisson', 'fish', 'n', 'm'],
  ['légume', 'vegetable', 'n', 'm'],
  ['fruit', 'fruit', 'n', 'm'],
  ['pomme', 'apple', 'n', 'f'],
  ['gâteau', 'cake', 'n', 'm'],
  ['sucre', 'sugar', 'n', 'm'],
  ['sel', 'salt', 'n', 'm'],
  ['repas', 'meal', 'n', 'm'],
  ['restaurant', 'restaurant', 'n', 'm'],
  ['hôtel', 'hotel', 'n', 'm'],
  ['addition', 'bill', 'n', 'f'],
  ['verre', 'glass', 'n', 'm'],
  ['assiette', 'plate', 'n', 'f'],
  ['couteau', 'knife', 'n', 'm'],
  ['bouteille', 'bottle', 'n', 'f'],
  ['chien', 'dog', 'n', 'm'],
  ['chat', 'cat', 'n', 'm'],
  ['oiseau', 'bird', 'n', 'm'],
  ['cheval', 'horse', 'n', 'm'],
  ['arbre', 'tree', 'n', 'm'],
  ['fleur', 'flower', 'n', 'f'],
  ['herbe', 'grass', 'n', 'f'],
  ['forêt', 'forest', 'n', 'f'],
  ['champ', 'field', 'n', 'm'],
  ['campagne', 'countryside', 'n', 'f'],
  ['mer', 'sea', 'n', 'f'],
  ['montagne', 'mountain', 'n', 'f'],
  ['plage', 'beach', 'n', 'f'],
  ['lac', 'lake', 'n', 'm'],
  ['rivière', 'river', 'n', 'f'],
  ['île', 'island', 'n', 'f'],
  ['ciel', 'sky', 'n', 'm'],
  ['soleil', 'sun', 'n', 'm'],
  ['lune', 'moon', 'n', 'f'],
  ['étoile', 'star', 'n', 'f'],
  ['pluie', 'rain', 'n', 'f'],
  ['neige', 'snow', 'n', 'f'],
  ['vent', 'wind', 'n', 'm'],
  ['orage', 'storm', 'n', 'm'],
  ['nuage', 'cloud', 'n', 'm'],
  ['saison', 'season', 'n', 'f'],
  ['été', 'summer', 'n', 'm'],
  ['hiver', 'winter', 'n', 'm'],
  ['printemps', 'spring', 'n', 'm'],
  ['automne', 'autumn', 'n', 'm'],
  ['feu', 'fire', 'n', 'm'],
  ['air', 'air', 'n', 'm'],
  ['terre', 'earth, ground', 'n', 'f'],
  ['pierre', 'stone', 'n', 'f'],
  ['amour', 'love', 'n', 'm'],
  ['peur', 'fear', 'n', 'f'],
  ['joie', 'joy', 'n', 'f'],
  ['colère', 'anger', 'n', 'f'],
  ['espoir', 'hope', 'n', 'm'],
  ['chance', 'luck', 'n', 'f'],
  ['vérité', 'truth', 'n', 'f'],
  ['mensonge', 'lie', 'n', 'm'],
  ['secret', 'secret', 'n', 'm'],
  ['souvenir', 'memory, souvenir', 'n', 'm'],
  ['rêve', 'dream', 'n', 'm'],
  ['envie', 'desire, craving', 'n', 'f'],
  ['besoin', 'need', 'n', 'm'],
  ['effort', 'effort', 'n', 'm'],
  ['sens', 'meaning, direction, sense', 'n', 'm'],
  ['ordre', 'order', 'n', 'm'],
  ['groupe', 'group', 'n', 'm'],
  ['manière', 'way, manner', 'n', 'f'],
  ['façon', 'way', 'n', 'f'],
  ['choix', 'choice', 'n', 'm'],
  ['avis', 'opinion', 'n', 'm'],
  ['début', 'beginning', 'n', 'm'],
  ['milieu', 'middle', 'n', 'm'],
  ['côté', 'side', 'n', 'm'],
  ['bout', 'end, tip', 'n', 'm'],
  ['moitié', 'half', 'n', 'f'],
  ['nombre', 'number, quantity', 'n', 'm'],
  ['numéro', 'number of a thing', 'n', 'm'],
  ['reste', 'rest, remainder', 'n', 'm'],
  ['police', 'police', 'n', 'f'],
  ['loi', 'law', 'n', 'f'],
  ['guerre', 'war', 'n', 'f'],
  ['paix', 'peace', 'n', 'f'],
  ['peuple', 'people, nation', 'n', 'm'],
  ['roi', 'king', 'n', 'm'],
  ['reine', 'queen', 'n', 'f'],
  ['président', 'president', 'n', 'm'],
  ['élection', 'election', 'n', 'f'],
  ['impôt', 'tax', 'n', 'm'],
  ['liberté', 'freedom', 'n', 'f'],
  ['droit', 'right, law', 'n', 'm'],
  ['état', 'state', 'n', 'm'],
  ['gouvernement', 'government', 'n', 'm'],
  ['société', 'society, company', 'n', 'f'],
  ['siècle', 'century', 'n', 'm'],
  ['musique', 'music', 'n', 'f'],
  ['film', 'film', 'n', 'm'],
  ['photo', 'photo', 'n', 'f'],
  ['journal', 'newspaper', 'n', 'm'],
  ['nouvelle', 'piece of news', 'n', 'f'],
  ['message', 'message', 'n', 'm'],
  ['téléphone', 'telephone', 'n', 'm'],
  ['ordinateur', 'computer', 'n', 'm'],
  ['jeu', 'game', 'n', 'm'],
  ['sport', 'sport', 'n', 'm'],
  ['équipe', 'team', 'n', 'f'],
  ['match', 'match', 'n', 'm'],
  ['vêtement', 'garment', 'n', 'm'],
  ['robe', 'dress', 'n', 'f'],
  ['pantalon', 'trousers', 'n', 'm'],
  ['chemise', 'shirt', 'n', 'f'],
  ['chaussure', 'shoe', 'n', 'f'],
  ['manteau', 'coat', 'n', 'm'],
  ['poche', 'pocket', 'n', 'f'],
  ['couleur', 'colour', 'n', 'f'],
  ['taille', 'size, waist', 'n', 'f'],
  ['poids', 'weight', 'n', 'm'],
  ['forme', 'shape, form', 'n', 'f'],
  ['joli', 'pretty', 'a', 'jolie'],
  ['propre', 'clean, own', 'a'],
  ['sale', 'dirty', 'a'],
  ['gratuit', 'free of charge', 'a', 'gratuite'],
  ['simple', 'simple', 'a'],
  ['compliqué', 'complicated', 'a', 'compliquée'],
  ['facile', 'easy', 'a'],
  ['difficile', 'difficult', 'a'],
  ['utile', 'useful', 'a'],
  ['inutile', 'useless', 'a'],
  ['possible', 'possible', 'a'],
  ['impossible', 'impossible', 'a'],
  ['important', 'important', 'a', 'importante'],
  ['sûr', 'sure, safe', 'a', 'sûre'],
  ['prêt', 'ready', 'a', 'prête'],
  ['vide', 'empty', 'a'],
  ['lourd', 'heavy', 'a', 'lourde'],
  ['léger', 'light in weight', 'a', 'légère'],
  ['rapide', 'fast', 'a'],
  ['lent', 'slow', 'a', 'lente'],
  ['haut', 'high', 'a', 'haute'],
  ['bas', 'low', 'a', 'basse'],
  ['proche', 'near, close', 'a'],
  ['doux', 'soft, sweet, mild', 'a', 'douce'],
  ['dur', 'hard, tough', 'a', 'dure'],
  ['meilleur', 'better, best', 'a', 'meilleure'],
  ['pire', 'worse, worst', 'a'],
  ['entier', 'whole', 'a', 'entière'],
  ['clair', 'clear, light', 'a', 'claire'],
  ['sombre', 'dark', 'a'],
  ['calme', 'calm, quiet', 'a'],
  ['bruyant', 'noisy', 'a', 'bruyante'],
  ['sérieux', 'serious', 'a', 'sérieuse'],
  ['célèbre', 'famous', 'a'],
  ['pauvre', 'poor', 'a'],
  ['riche', 'rich', 'a'],
  ['heureux', 'happy', 'a', 'heureuse'],
  ['triste', 'sad', 'a'],
  ['content', 'pleased', 'a', 'contente'],
  ['fatigué', 'tired', 'a', 'fatiguée'],
  ['malade', 'ill', 'a'],
  ['libre', 'free, available', 'a'],
  ['occupé', 'busy, taken', 'a', 'occupée'],
  ['gentil', 'kind', 'a', 'gentille'],
  ['drôle', 'funny', 'a'],
  ['méchant', 'nasty', 'a', 'méchante'],
  ['prochain', 'next', 'a', 'prochaine'],
  ['différent', 'different', 'a', 'différente'],
  ['pareil', 'the same, alike', 'a', 'pareille'],
  ['chaud', 'hot, warm', 'a', 'chaude'],
  ['froid', 'cold', 'a', 'froide'],
  ['frais', 'fresh, cool', 'a', 'fraîche'],
  ['sec', 'dry', 'a', 'sèche'],
  ['mouillé', 'wet', 'a', 'mouillée'],
  ['rouge', 'red', 'a'],
  ['bleu', 'blue', 'a', 'bleue'],
  ['vert', 'green', 'a', 'verte'],
  ['jaune', 'yellow', 'a'],
  ['gris', 'grey', 'a', 'grise'],
  ['brun', 'brown', 'a', 'brune'],
  ['rose', 'pink', 'a'],
  ['court', 'short', 'a', 'courte'],
  ['large', 'wide', 'a'],
  ['étroit', 'narrow', 'a', 'étroite'],
  ['profond', 'deep', 'a', 'profonde'],
  ['épais', 'thick', 'a', 'épaisse'],
  ['mince', 'thin, slim', 'a'],
  ['plat', 'flat', 'a', 'plate'],
  ['rond', 'round', 'a', 'ronde'],
  ['carré', 'square', 'a', 'carrée'],
  ['naturel', 'natural', 'a', 'naturelle'],
  ['normal', 'normal', 'a', 'normale'],
  ['bizarre', 'strange', 'a'],
  ['certain', 'certain, some', 'a', 'certaine'],
  ['plusieurs', 'several', 'a'],
  ['chaque', 'each', 'a'],
  ['tout', 'all, every', 'a', 'toute'],
  ['quelque', 'some', 'a'],
  ['aucun', 'no, none', 'a', 'aucune'],
  ['se lever', 'to get up', 'v'],
  ['se coucher', 'to go to bed', 'v'],
  ['se réveiller', 'to wake up', 'v'],
  ['se dépêcher', 'to hurry', 'v'],
  ['s’asseoir', 'to sit down', 'v'],
  ['se souvenir', 'to remember', 'v'],
  ['s’habiller', 'to get dressed', 'v'],
  ['se promener', 'to go for a walk', 'v'],
  ['se tromper', 'to be mistaken', 'v'],
  ['s’ennuyer', 'to be bored', 'v'],
  ['se laver', 'to wash', 'v'],
  ['se reposer', 'to rest', 'v'],
  ['s’occuper', 'to take care of', 'v'],
  ['s’inquiéter', 'to worry', 'v'],
  ['se passer', 'to happen', 'v'],
  ['se trouver', 'to be located', 'v'],
  ['appartenir', 'to belong', 'v'],
  ['nourrir', 'to feed', 'v'],
  ['cuisiner', 'to cook', 'v'],
  ['nettoyer', 'to clean', 'v'],
  ['ranger', 'to tidy up', 'v'],
  ['réparer', 'to repair', 'v'],
  ['casser', 'to break', 'v'],
  ['couper', 'to cut', 'v'],
  ['tirer', 'to pull, to shoot', 'v'],
  ['pousser', 'to push, to grow', 'v'],
  ['jeter', 'to throw', 'v'],
  ['lancer', 'to throw, to launch', 'v'],
  ['attraper', 'to catch', 'v'],
  ['toucher', 'to touch', 'v'],
  ['tourner', 'to turn', 'v'],
  ['traverser', 'to cross', 'v'],
  ['avancer', 'to move forward', 'v'],
  ['reculer', 'to move back', 'v'],
  ['sauter', 'to jump', 'v'],
  ['voler', 'to fly, to steal', 'v'],
  ['nager', 'to swim', 'v'],
  ['tuer', 'to kill', 'v'],
  ['blesser', 'to injure', 'v'],
  ['soigner', 'to treat, to look after', 'v'],
  ['guérir', 'to cure, to get better', 'v'],
  ['mourir', 'to die', 'v'],
  ['naître', 'to be born', 'v'],
  ['grandir', 'to grow up', 'v'],
  ['vieillir', 'to grow old', 'v'],
  ['durer', 'to last', 'v'],
  ['commander', 'to order', 'v'],
  ['vendre', 'to sell', 'v'],
  ['louer', 'to rent, to praise', 'v'],
  ['prêter', 'to lend', 'v'],
  ['emprunter', 'to borrow', 'v'],
  ['dépenser', 'to spend money', 'v'],
  ['économiser', 'to save money', 'v'],
  ['préparer', 'to prepare', 'v'],
  ['organiser', 'to organise', 'v'],
  ['participer', 'to take part', 'v'],
  ['présenter', 'to introduce, to present', 'v'],
  ['proposer', 'to suggest', 'v'],
  ['accepter', 'to accept', 'v'],
  ['refuser', 'to refuse', 'v'],
  ['promettre', 'to promise', 'v'],
  ['mentir', 'to lie', 'v'],
  ['avouer', 'to admit', 'v'],
  ['cacher', 'to hide', 'v'],
  ['découvrir', 'to discover', 'v'],
  ['rendre visite', 'to visit someone', 'v'],
  ['visiter', 'to visit a place', 'v'],
  ['emmener', 'to take someone along', 'v'],
  ['amener', 'to bring someone', 'v'],
  ['ramener', 'to bring back', 'v'],
  ['rentrer', 'to go home, to go back in', 'v'],
  ['retourner', 'to return, to turn over', 'v'],
  ['quitter', 'to leave someone or somewhere', 'v'],
  ['abandonner', 'to give up', 'v'],
  ['oser', 'to dare', 'v'],
  ['espérer', 'to hope', 'v'],
  ['craindre', 'to fear', 'v'],
  ['regretter', 'to regret, to miss', 'v'],
  ['excuser', 'to excuse', 'v'],
  ['pardonner', 'to forgive', 'v'],
  ['féliciter', 'to congratulate', 'v'],
  ['conseiller', 'to advise', 'v'],
  ['prévenir', 'to warn, to let know', 'v'],
  ['sonner', 'to ring', 'v'],
  ['frapper', 'to knock, to hit', 'v'],
  ['allumer', 'to switch on', 'v'],
  ['éteindre', 'to switch off', 'v'],
  ['brûler', 'to burn', 'v'],
  ['geler', 'to freeze', 'v'],
  ['pleuvoir', 'to rain', 'v'],
  ['neiger', 'to snow', 'v'],
  ['briller', 'to shine', 'v'],
  ['ressembler', 'to resemble', 'v'],
  ['comparer', 'to compare', 'v'],
  ['mesurer', 'to measure', 'v'],
  ['peser', 'to weigh', 'v'],
  ['remplir', 'to fill', 'v'],
  ['vider', 'to empty', 'v'],
  ['partager', 'to share', 'v'],
  ['séparer', 'to separate', 'v'],
  ['mélanger', 'to mix', 'v'],
  ['couvrir', 'to cover', 'v'],
  ['entourer', 'to surround', 'v'],
  ['dépasser', 'to overtake, to exceed', 'v'],
  ['garer', 'to park', 'v'],
  ['rouler', 'to drive along, to roll', 'v'],
  ['atterrir', 'to land', 'v'],
  ['décoller', 'to take off', 'v'],
  ['réserver', 'to book', 'v'],
  ['annuler', 'to cancel', 'v'],
  ['retarder', 'to delay', 'v'],
  ['seconde', 'second', 'n', 'f'],
  ['midi', 'midday', 'n', 'm'],
  ['minuit', 'midnight', 'n', 'm'],
  ['journée', 'day as a span', 'n', 'f'],
  ['soirée', 'evening as a span', 'n', 'f'],
  ['weekend', 'weekend', 'n', 'm'],
  ['anniversaire', 'birthday, anniversary', 'n', 'm'],
  ['fête', 'party, festival', 'n', 'f'],
  ['cadeau', 'present', 'n', 'm'],
  ['rendez-vous', 'appointment, meeting', 'n', 'm'],
  ['retard', 'delay, lateness', 'n', 'm'],
  ['avance', 'advance, lead', 'n', 'f'],
  ['habitude', 'habit', 'n', 'f'],
  ['expérience', 'experience, experiment', 'n', 'f'],
  ['cas', 'case', 'n', 'm'],
  ['situation', 'situation', 'n', 'f'],
  ['condition', 'condition', 'n', 'f'],
  ['résultat', 'result', 'n', 'm'],
  ['effet', 'effect', 'n', 'm'],
  ['cause', 'cause', 'n', 'f'],
  ['but', 'aim, goal', 'n', 'm'],
  ['moyen', 'means, way', 'n', 'm'],
  ['service', 'service, favour', 'n', 'm'],
  ['aide', 'help', 'n', 'f'],
  ['conseil', 'piece of advice', 'n', 'm'],
  ['règle', 'rule, ruler', 'n', 'f'],
  ['erreur', 'mistake', 'n', 'f'],
  ['faute', 'fault, mistake', 'n', 'f'],
  ['échec', 'failure', 'n', 'm'],
  ['risque', 'risk', 'n', 'm'],
  ['danger', 'danger', 'n', 'm'],
  ['sécurité', 'safety', 'n', 'f'],
  ['force', 'strength, force', 'n', 'f'],
  ['pouvoir', 'power', 'n', 'm'],
  ['niveau', 'level', 'n', 'm'],
  ['qualité', 'quality', 'n', 'f'],
  ['défaut', 'flaw', 'n', 'm'],
  ['valeur', 'value', 'n', 'f'],
  ['sorte', 'sort, kind', 'n', 'f'],
  ['espèce', 'species, kind', 'n', 'f'],
  ['type', 'type, bloke', 'n', 'm'],
  ['genre', 'kind, gender', 'n', 'm'],
  ['image', 'picture, image', 'n', 'f'],
  ['dessin', 'drawing', 'n', 'm'],
  ['lumière', 'light', 'n', 'f'],
  ['ombre', 'shadow, shade', 'n', 'f'],
  ['bruit', 'noise', 'n', 'm'],
  ['silence', 'silence', 'n', 'm'],
  ['voix', 'voice', 'n', 'f'],
  ['chanson', 'song', 'n', 'f'],
  ['phrase', 'sentence', 'n', 'f'],
  ['langue', 'language, tongue', 'n', 'f'],
  ['mémoire', 'memory', 'n', 'f'],
  ['esprit', 'mind, spirit', 'n', 'm'],
  ['âme', 'soul', 'n', 'f'],
  ['pensée', 'thought', 'n', 'f'],
  ['sentiment', 'feeling', 'n', 'm'],
  ['caractère', 'character', 'n', 'm'],
  ['humeur', 'mood', 'n', 'f'],
  ['sourire', 'smile', 'n', 'm'],
  ['larme', 'tear', 'n', 'f'],
  ['cri', 'shout, cry', 'n', 'm'],
  ['geste', 'gesture', 'n', 'm'],
  ['pas', 'step', 'n', 'm'],
  ['saut', 'jump', 'n', 'm'],
  ['course', 'race, errand', 'n', 'f'],
  ['promenade', 'walk', 'n', 'f'],
  ['visite', 'visit', 'n', 'f'],
  ['départ', 'departure', 'n', 'm'],
  ['arrivée', 'arrival', 'n', 'f'],
  ['entrée', 'entrance, starter', 'n', 'f'],
  ['sortie', 'exit, outing', 'n', 'f'],
  ['passage', 'passage, way through', 'n', 'm'],
  ['pont', 'bridge', 'n', 'm'],
  ['tour', 'turn, trick, tower', 'n', 'm'],
  ['coin', 'corner', 'n', 'm'],
  ['bord', 'edge, shore', 'n', 'm'],
  ['fond', 'bottom, back', 'n', 'm'],
  ['surface', 'surface', 'n', 'f'],
  ['espace', 'space', 'n', 'm'],
  ['distance', 'distance', 'n', 'f'],
  ['direction', 'direction', 'n', 'f'],
  ['plan', 'plan, street map', 'n', 'm'],
  ['région', 'region', 'n', 'f'],
  ['endroit', 'place, spot', 'n', 'm'],
  ['lieu', 'place', 'n', 'm'],
  ['coût', 'cost', 'n', 'm'],
  ['somme', 'sum, amount', 'n', 'f'],
  ['compte', 'account, count', 'n', 'm'],
  ['banque', 'bank', 'n', 'f'],
  ['monnaie', 'change, currency', 'n', 'f'],
  ['facture', 'invoice', 'n', 'f'],
  ['dette', 'debt', 'n', 'f'],
  ['contrat', 'contract', 'n', 'm'],
  ['papier', 'paper', 'n', 'm'],
  ['document', 'document', 'n', 'm'],
  ['dossier', 'file, case', 'n', 'm'],
  ['formulaire', 'form', 'n', 'm'],
  ['signature', 'signature', 'n', 'f'],
  ['adresse', 'address', 'n', 'f'],
  ['courrier', 'post, mail', 'n', 'm'],
  ['colis', 'parcel', 'n', 'm'],
  ['timbre', 'stamp', 'n', 'm'],
  ['boîte', 'box', 'n', 'f'],
  ['objet', 'object', 'n', 'm'],
  ['outil', 'tool', 'n', 'm'],
  ['machine', 'machine', 'n', 'f'],
  ['moteur', 'engine', 'n', 'm'],
  ['roue', 'wheel', 'n', 'f'],
  ['clou', 'nail', 'n', 'm'],
  ['fil', 'thread, wire', 'n', 'm'],
  ['bois', 'wood', 'n', 'm'],
  ['métal', 'metal', 'n', 'm'],
  ['tissu', 'fabric', 'n', 'm'],
  ['cuir', 'leather', 'n', 'm'],
  ['or', 'gold', 'n', 'm'],
  ['fer', 'iron', 'n', 'm'],
  ['plastique', 'plastic', 'n', 'm'],
  ['poussière', 'dust', 'n', 'f'],
  ['boue', 'mud', 'n', 'f'],
  ['sable', 'sand', 'n', 'm'],
  ['glace', 'ice, ice cream, mirror', 'n', 'f'],
  ['odeur', 'smell', 'n', 'f'],
  ['goût', 'taste', 'n', 'm'],
  ['faim', 'hunger', 'n', 'f'],
  ['soif', 'thirst', 'n', 'f'],
  ['repos', 'rest', 'n', 'm'],
  ['fatigue', 'tiredness', 'n', 'f'],
  ['jeunesse', 'youth', 'n', 'f'],
  ['enfance', 'childhood', 'n', 'f'],
  ['âge', 'age', 'n', 'm'],
  ['naissance', 'birth', 'n', 'f'],
  ['mort', 'death', 'n', 'f'],
  ['mariage', 'marriage, wedding', 'n', 'm'],
  ['divorce', 'divorce', 'n', 'm'],
  ['amitié', 'friendship', 'n', 'f'],
  ['confiance', 'trust', 'n', 'f'],
  ['respect', 'respect', 'n', 'm'],
  ['courage', 'courage', 'n', 'm'],
  ['patience', 'patience', 'n', 'f'],
  ['orgueil', 'pride', 'n', 'm'],
  ['jalousie', 'jealousy', 'n', 'f'],
  ['surprise', 'surprise', 'n', 'f'],
  ['inquiétude', 'worry', 'n', 'f'],
  ['tristesse', 'sadness', 'n', 'f'],
  ['bonheur', 'happiness', 'n', 'm'],
  ['malheur', 'misfortune', 'n', 'm'],
  ['plaisir', 'pleasure', 'n', 'm'],
  ['intérêt', 'interest', 'n', 'm'],
  ['curiosité', 'curiosity', 'n', 'f'],
  ['attention', 'attention, care', 'n', 'f'],
  ['soin', 'care', 'n', 'm'],
  ['propreté', 'cleanliness', 'n', 'f'],
  ['ménage', 'housework, household', 'n', 'm'],
  ['linge', 'laundry', 'n', 'm'],
  ['savon', 'soap', 'n', 'm'],
  ['serviette', 'towel, napkin', 'n', 'f'],
  ['brosse', 'brush', 'n', 'f'],
  ['miroir', 'mirror', 'n', 'm'],
  ['douche', 'shower', 'n', 'f'],
  ['bain', 'bath', 'n', 'm'],
  ['toilettes', 'toilet', 'n', 'f-pl'],
  ['meuble', 'piece of furniture', 'n', 'm'],
  ['armoire', 'wardrobe', 'n', 'f'],
  ['tiroir', 'drawer', 'n', 'm'],
  ['étagère', 'shelf', 'n', 'f'],
  ['canapé', 'sofa', 'n', 'm'],
  ['fauteuil', 'armchair', 'n', 'm'],
  ['tapis', 'carpet, rug', 'n', 'm'],
  ['rideau', 'curtain', 'n', 'm'],
  ['lampe', 'lamp', 'n', 'f'],
  ['four', 'oven', 'n', 'm'],
  ['frigo', 'fridge', 'n', 'm'],
  ['casserole', 'saucepan', 'n', 'f'],
  ['cuillère', 'spoon', 'n', 'f'],
  ['fourchette', 'fork', 'n', 'f'],
  ['tasse', 'cup', 'n', 'f'],
  ['nappe', 'tablecloth', 'n', 'f'],
  ['petit-déjeuner', 'breakfast', 'n', 'm'],
  ['déjeuner', 'lunch', 'n', 'm'],
  ['dîner', 'dinner', 'n', 'm'],
  ['plat', 'dish, course', 'n', 'm'],
  ['dessert', 'dessert', 'n', 'm'],
  ['recette', 'recipe', 'n', 'f'],
  ['boisson', 'drink', 'n', 'f'],
  ['bière', 'beer', 'n', 'f'],
  ['jus', 'juice', 'n', 'm'],
  ['thé', 'tea', 'n', 'm'],
  ['beurre', 'butter', 'n', 'm'],
  ['œuf', 'egg', 'n', 'm'],
  ['riz', 'rice', 'n', 'm'],
  ['pâtes', 'pasta', 'n', 'f-pl'],
  ['soupe', 'soup', 'n', 'f'],
  ['salade', 'salad, lettuce', 'n', 'f'],
  ['tomate', 'tomato', 'n', 'f'],
  ['pomme de terre', 'potato', 'n', 'f'],
  ['carotte', 'carrot', 'n', 'f'],
  ['oignon', 'onion', 'n', 'm'],
  ['poulet', 'chicken', 'n', 'm'],
  ['bœuf', 'beef', 'n', 'm'],
  ['porc', 'pork', 'n', 'm'],
  ['jambon', 'ham', 'n', 'm'],
  ['chocolat', 'chocolate', 'n', 'm'],
  ['bonbon', 'sweet', 'n', 'm'],
  ['orange', 'orange', 'n', 'f'],
  ['banane', 'banana', 'n', 'f'],
  ['fraise', 'strawberry', 'n', 'f'],
  ['raisin', 'grape', 'n', 'm'],
  ['citron', 'lemon', 'n', 'm'],
  ['boulangerie', 'bakery', 'n', 'f'],
  ['boucherie', 'butcher’s', 'n', 'f'],
  ['supermarché', 'supermarket', 'n', 'm'],
  ['caisse', 'till, checkout', 'n', 'f'],
  ['rayon', 'aisle, department', 'n', 'm'],
  ['vendeur', 'shop assistant', 'n', 'm'],
  ['serveur', 'waiter', 'n', 'm'],
  ['cuisinier', 'cook', 'n', 'm'],
  ['coiffeur', 'hairdresser', 'n', 'm'],
  ['facteur', 'postman', 'n', 'm'],
  ['pompier', 'firefighter', 'n', 'm'],
  ['agriculteur', 'farmer', 'n', 'm'],
  ['avocat', 'lawyer, avocado', 'n', 'm'],
  ['infirmier', 'nurse', 'n', 'm'],
  ['ingénieur', 'engineer', 'n', 'm'],
  ['chercheur', 'researcher', 'n', 'm'],
  ['écrivain', 'writer', 'n', 'm'],
  ['artiste', 'artist', 'n', 'mf'],
  ['acteur', 'actor', 'n', 'm'],
  ['chanteur', 'singer', 'n', 'm'],
  ['peintre', 'painter', 'n', 'm'],
  ['tableau', 'painting, board', 'n', 'm'],
  ['théâtre', 'theatre', 'n', 'm'],
  ['musée', 'museum', 'n', 'm'],
  ['église', 'church', 'n', 'f'],
  ['château', 'castle', 'n', 'm'],
  ['parc', 'park', 'n', 'm'],
  ['piscine', 'swimming pool', 'n', 'f'],
  ['stade', 'stadium', 'n', 'm'],
  ['cinéma', 'cinema', 'n', 'm'],
  ['spectacle', 'show', 'n', 'm'],
  ['siège', 'seat', 'n', 'm'],
  ['scène', 'stage, scene', 'n', 'f'],
  ['public', 'audience', 'n', 'm'],
  ['souris', 'mouse', 'n', 'f'],
  ['écran', 'screen', 'n', 'm'],
  ['clavier', 'keyboard', 'n', 'm'],
  ['fichier', 'file', 'n', 'm'],
  ['site', 'website', 'n', 'm'],
  ['réseau', 'network', 'n', 'm'],
  ['mot de passe', 'password', 'n', 'm'],
  ['appareil', 'device', 'n', 'm'],
  ['pile', 'battery', 'n', 'f'],
  ['prise', 'socket, plug', 'n', 'f'],
  ['chaleur', 'heat', 'n', 'f'],
  ['température', 'temperature', 'n', 'f'],
  ['degré', 'degree', 'n', 'm'],
  ['mètre', 'metre', 'n', 'm'],
  ['kilomètre', 'kilometre', 'n', 'm'],
  ['kilo', 'kilo', 'n', 'm'],
  ['litre', 'litre', 'n', 'm'],
  ['dizaine', 'about ten', 'n', 'f'],
  ['centaine', 'about a hundred', 'n', 'f'],
  ['millier', 'about a thousand', 'n', 'm'],
  ['million', 'million', 'n', 'm'],
  ['tiers', 'third', 'n', 'm'],
  ['quart', 'quarter', 'n', 'm'],
  ['ensuite', 'next, afterwards', 'x'],
  ['d’abord', 'first of all', 'x'],
  ['pourtant', 'yet, however', 'x'],
  ['cependant', 'however', 'x'],
  ['malgré', 'despite', 'x'],
  ['selon', 'according to', 'x'],
  ['parmi', 'among', 'x'],
  ['jusqu’à', 'until, as far as', 'x'],
  ['dès', 'as soon as, from', 'x'],
  ['sauf', 'except', 'x'],
  ['plutôt', 'rather', 'x'],
  ['environ', 'about, roughly', 'x'],
  ['tout à fait', 'quite, entirely', 'x'],
  ['tout de suite', 'right away', 'x'],
  ['en train de', 'in the middle of', 'x'],
  ['à peu près', 'more or less', 'x'],
  ['par exemple', 'for example', 'x'],
  ['bien sûr', 'of course', 'x'],
  ['au moins', 'at least', 'x'],
  ['au lieu de', 'instead of', 'x'],
  ['grâce à', 'thanks to', 'x'],
  ['à cause de', 'because of', 'x'],
  ['afin de', 'in order to', 'x'],
  ['sans doute', 'probably', 'x'],
  ['en effet', 'indeed', 'x'],
  ['par contre', 'on the other hand', 'x'],
  ['de nouveau', 'again', 'x'],
  ['de plus en plus', 'more and more', 'x'],
  ['tout le monde', 'everyone', 'x'],
  ['quelque chose', 'something', 'x'],
  ['quelqu’un', 'someone', 'x'],
  ['rien', 'nothing', 'x'],
  ['personne ne', 'nobody', 'x'],
  ['n’importe quoi', 'anything, nonsense', 'x'],
  ['n’importe où', 'anywhere', 'x'],
  ['autrement', 'otherwise', 'x'],
  ['ainsi', 'thus, in this way', 'x'],
  ['soudain', 'suddenly', 'x'],
  ['debout', 'standing up', 'x'],
  ['exprès', 'on purpose', 'x'],
  ['par hasard', 'by chance', 'x'],
  ['à nouveau', 'once again', 'x'],
  ['en retard', 'late', 'x'],
  ['à l’heure', 'on time', 'x'],
  ['en avance', 'early', 'x'],
  ['vitesse', 'speed', 'n', 'f'],
  ['retour', 'return', 'n', 'm'],
  ['congé', 'time off', 'n', 'm'],
  ['permis', 'licence, permit', 'n', 'm'],
  ['passeport', 'passport', 'n', 'm'],
  ['frontière', 'border', 'n', 'f'],
  ['bagage', 'piece of luggage', 'n', 'm'],
  ['quai', 'platform, quay', 'n', 'm'],
  ['arrêt', 'stop', 'n', 'm'],
  ['trajet', 'journey, trip', 'n', 'm'],
  ['essence', 'petrol', 'n', 'f'],
  ['panne', 'breakdown', 'n', 'f'],
  ['pneu', 'tyre', 'n', 'm'],
  ['chaussette', 'sock', 'n', 'f'],
  ['pull', 'jumper', 'n', 'm'],
  ['veste', 'jacket', 'n', 'f'],
  ['ceinture', 'belt', 'n', 'f'],
  ['chapeau', 'hat', 'n', 'm'],
  ['lunettes', 'glasses', 'n', 'f-pl'],
  ['montre', 'watch', 'n', 'f'],
  ['parapluie', 'umbrella', 'n', 'm'],
  ['portefeuille', 'wallet', 'n', 'm'],
  ['animal', 'animal', 'n', 'm'],
  ['plante', 'plant', 'n', 'f'],
  ['feuille', 'leaf, sheet', 'n', 'f'],
  ['branche', 'branch', 'n', 'f'],
  ['nature', 'nature', 'n', 'f'],
  ['planète', 'planet', 'n', 'f'],
  ['souffrir', 'to suffer', 'v'],
  ['accompagner', 'to go with', 'v'],
  ['disparaître', 'to disappear', 'v'],
  ['apparaître', 'to appear', 'v'],
  ['exister', 'to exist', 'v'],
];

const VOWEL = /^[aeiouyàâäéèêëîïôöùûü]/i;

/** Whether the article runs into the word: l’eau, l’homme — but le hasard. */
const elides = (word) => VOWEL.test(word) || (word.startsWith('h') && !ASPIRATED.has(word));

/**
 * The French side of the card. A noun is never shown bare: it arrives with
 * its article, because that is the half people fail to learn. Where the
 * article elides and hides the gender — l’eau could be either — the gender
 * is spelt out instead.
 */
function shown(word, kind, extra) {
  if (kind === 'a') return extra ? `${word} (${extra})` : word;
  if (kind !== 'n') return word;
  if (extra.endsWith('-pl')) return `les ${word} (${extra[0]} pl)`;
  if (extra === 'mf') return elides(word) ? `l’${word} (m/f)` : `le/la ${word}`;
  if (elides(word)) return `l’${word} (${extra})`;
  return `${extra === 'm' ? 'le' : 'la'} ${word}`;
}

/**
 * What counts as having produced the word. For a noun that means an article
 * that proves you know the gender, which is why l’eau is not on this list:
 * it is what you would write, but it says nothing about which one it is.
 */
function accepts(word, kind, extra) {
  if (kind === 'a') return extra ? [word, extra] : [word];
  if (kind !== 'n') return [word];
  if (extra.endsWith('-pl')) return [`les ${word}`, `des ${word}`];
  // Before a vowel the definite article elides and stops proving anything —
  // l'eau could be either — so those words are only answered with un or une.
  if (elides(word)) {
    if (extra === 'mf') return [`un ${word}`, `une ${word}`];
    return [`${extra === 'm' ? 'un' : 'une'} ${word}`];
  }
  if (extra === 'mf') return ['le', 'la', 'un', 'une'].map((a) => `${a} ${word}`);
  return extra === 'm' ? [`le ${word}`, `un ${word}`] : [`la ${word}`, `une ${word}`];
}

const slug = (value) => value.normalize('NFD').replace(/[̀-ͯ]/g, '')
  .toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

const bandOf = (rank) => BANDS.find((band) => rank >= band.from && rank < band.to).id;

export const WORDS = RAW.map(([word, en, kind, extra], rank) => ({
  word,
  en,
  kind,
  rank,
  band: bandOf(rank),
  gender: kind === 'n' ? extra : null,
  feminine: kind === 'a' ? (extra ?? word) : null,
  shown: shown(word, kind, extra),
  accepts: accepts(word, kind, extra),
  // The id carries the kind, so a word that is both can be both: le sourire
  // and sourire are two cards.
  id: `${slug(word)}-${kind}`,
}));

export const WORD_BY_ID = new Map(WORDS.map((entry) => [entry.id, entry]));

export const wordsFor = (bands, kinds) =>
  WORDS.filter((entry) => bands.includes(entry.band) && kinds.includes(entry.kind));
